"""Which runtime answers an interactive research question.

Two implementations of one behavioural contract, selected by
``Settings.agent_runtime`` (requirement 49). Default ``legacy``
(requirement 51's rollback), and the choice is recorded on the result so
provenance says which engine produced an answer -- historical rows are
never rewritten to claim otherwise (requirement 6).

What this selector is NOT: a methodology switch. The official V4 forward
DecisionView does not pass through either runtime -- it is generated by
``services/v4_shadow_orchestration.py::default_view_generator``, which
calls the provider directly -- so this flag cannot reach it in either
position. That is asserted in tests/test_agent_runtime_isolation.py rather
than left as a claim.
"""

import enum

from agents.graph.state import AGENT_RUNTIME_LANGGRAPH, AGENT_RUNTIME_LEGACY


class AgentRuntime(enum.StrEnum):
    LEGACY = "legacy"
    LANGGRAPH = "langgraph"

    @property
    def version(self) -> str:
        """The persisted runtime identity, as opposed to the flag value."""
        return (
            AGENT_RUNTIME_LEGACY
            if self is AgentRuntime.LEGACY
            else AGENT_RUNTIME_LANGGRAPH
        )


DEFAULT_AGENT_RUNTIME = AgentRuntime.LEGACY


def resolve_agent_runtime(configured: str | None) -> AgentRuntime:
    """Unknown values fall back to legacy rather than raising.

    Deliberate: a typo in AGENT_RUNTIME should not take AI Research down,
    and legacy is the behaviour the project already trusts. The fallback is
    reported by ``runtime_warning`` so it is visible rather than silent.
    """
    if configured is None:
        return DEFAULT_AGENT_RUNTIME
    try:
        return AgentRuntime(configured.strip().lower())
    except ValueError:
        return DEFAULT_AGENT_RUNTIME


def runtime_warning(configured: str | None) -> str | None:
    resolved = resolve_agent_runtime(configured)
    if configured and configured.strip().lower() != resolved.value:
        return (
            f"AGENT_RUNTIME is set to {configured!r}, which is not a known runtime; "
            f"using {resolved.value!r}."
        )
    return None
