"""Structural isolation for the agentic research layer
(requirements 78-81, 16, 52, 55, 90).

Same approach as tests/test_v4_4c_shadow_isolation.py: these walk the
real import graph with ``ast`` rather than reading docstrings, so each
guarantee is a checkable fact that fails the moment it stops holding --
which is exactly when a person should be asked, not after the first
forward sample has been contaminated.
"""

import ast
import os
from pathlib import Path

import pytest

_SRC = Path(__file__).resolve().parents[1] / "src"

#: Every module in the agentic research layer.
AGENT_RUNTIME_MODULES = (
    "agents/graph/state.py",
    "agents/graph/deps.py",
    "agents/graph/nodes.py",
    "agents/graph/quality.py",
    "agents/graph/workflow.py",
    "agents/graph/runtime.py",
    "agents/graph/checkpoint.py",
    "agents/adapters/model.py",
    "agents/adapters/tools.py",
    "agents/adapters/structured.py",
    "agents/adapters/retriever.py",
    "agents/runtime.py",
)

#: The deterministic financial engine. Strike geometry, expected move,
#: candidate construction, T+1 valuation, ranking, risk, capital, sizing,
#: entry and settlement. The research layer must not reach ANY of it.
DETERMINISTIC_ENGINE_PREFIXES = (
    "analytics.decision.",
    "analytics.options.strategy_candidates",
    "services.v4_",
    "services.v4_2_",
)

#: Modules that produce official forward evidence. These must not reach
#: either agent runtime (requirement 79).
OFFICIAL_FORWARD_MODULES = (
    "services/v4_shadow_orchestration.py",
    "services/v4_shadow.py",
    "services/v4_shadow_assembler.py",
    "services/v4_shadow_scheduler.py",
    "services/v4_2_challenger.py",
    "services/v4_2_phase2.py",
    "services/v4_2_parallel.py",
)

AGENT_RUNTIME_IMPORT_PREFIXES = ("agents.graph", "agents.adapters", "agents.orchestrator")


def _imports(relative_path: str) -> set[str]:
    """Every module name this file imports, including inside functions --
    this project uses deferred imports heavily, so a module-level-only
    check would miss most of them."""
    tree = ast.parse((_SRC / relative_path).read_text())
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            found.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            found.add(node.module)
            found.update(f"{node.module}.{alias.name}" for alias in node.names)
    return found


# --- requirement 78: the graph does not touch the V4 engine ------------


@pytest.mark.parametrize("module", AGENT_RUNTIME_MODULES)
def test_the_research_layer_cannot_reach_the_deterministic_engine(module):
    offending = sorted(
        name
        for name in _imports(module)
        for prefix in DETERMINISTIC_ENGINE_PREFIXES
        if name.startswith(prefix)
    )
    assert not offending, (
        f"{module} imports {offending}. Strikes, expected move, ranking, risk, "
        f"capital, sizing, entry and settlement stay deterministic Python -- the "
        f"research layer produces judgement and evidence, nothing else."
    )


def test_no_agent_module_imports_an_options_pricing_or_sizing_function():
    """Belt and braces on requirement 78: named functions, not just
    package prefixes."""
    forbidden = (
        "black_scholes",
        "max_defined_risk",
        "position_size",
        "choose_v4_2_candidate",
        "rank_candidates",
        "compute_entry_exit_schedule",
    )
    for module in AGENT_RUNTIME_MODULES:
        text = (_SRC / module).read_text()
        for name in forbidden:
            assert name not in text, f"{module} references {name}"


# --- requirement 79: the forward path stays legacy --------------------


@pytest.mark.parametrize("module", OFFICIAL_FORWARD_MODULES)
def test_the_official_forward_path_does_not_use_either_agent_runtime(module):
    offending = sorted(
        name
        for name in _imports(module)
        for prefix in AGENT_RUNTIME_IMPORT_PREFIXES
        if name.startswith(prefix)
    )
    assert not offending, (
        f"{module} imports {offending}. The official V4 forward DecisionView is "
        f"generated by default_view_generator calling the provider directly; routing "
        f"it through an orchestrator would confound a candidate-search change with a "
        f"research-orchestration change."
    )


def test_the_forward_view_generator_still_calls_the_provider_directly():
    """The positive half of requirement 79: assert what it DOES do, so a
    future refactor that routes it through the graph fails here."""
    text = (_SRC / "services/v4_shadow_orchestration.py").read_text()
    assert "generate_structured_result(" in text
    assert "DecisionView" in text
    assert "run_research_graph" not in text
    assert "AgentOrchestrator" not in text


def test_the_runtime_flag_defaults_to_legacy(monkeypatch):
    """The CODE default, not the ambient one.

    ``Settings()`` reads the project .env and the process environment, so a
    bare ``Settings()`` here asserted "this operator has not switched the
    flag on" rather than "the default is legacy" -- and went red the moment
    the flag was genuinely activated in production (2026-10-01). Both
    sources are removed so the assertion is about the code.
    """
    from agents.runtime import DEFAULT_AGENT_RUNTIME, AgentRuntime
    from core.config import Settings

    monkeypatch.delenv("AGENT_RUNTIME", raising=False)
    monkeypatch.delenv("AGENT_GRAPH_CHECKPOINTING_ENABLED", raising=False)

    assert DEFAULT_AGENT_RUNTIME is AgentRuntime.LEGACY
    assert Settings(_env_file=None).agent_runtime == "legacy"
    assert Settings(_env_file=None).agent_graph_checkpointing_enabled is False


def test_an_unknown_runtime_falls_back_to_legacy_and_says_so():
    from agents.runtime import AgentRuntime, resolve_agent_runtime, runtime_warning

    assert resolve_agent_runtime("langraph") is AgentRuntime.LEGACY
    assert "not a known runtime" in (runtime_warning("langraph") or "")
    assert runtime_warning("langgraph") is None


# --- requirement 16: no execution tool anywhere ------------------------


def test_no_brokerage_execution_tool_exists_in_the_tool_layer():
    for path in sorted((_SRC / "agents").rglob("*.py")):
        text = path.read_text()
        tree = ast.parse(text)
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if (
                        isinstance(target, ast.Name)
                        and target.id == "name"
                        and isinstance(node.value, ast.Constant)
                        and isinstance(node.value.value, str)
                    ):
                        value = node.value.value.lower()
                        for fragment in ("order", "exercise", "execute_trade"):
                            assert fragment not in value, (
                                f"{path.name} declares a tool named "
                                f"{node.value.value!r}"
                            )


def test_the_tool_layer_does_not_import_an_order_placing_client():
    """Checked as real imports rather than as substrings: agents/adapters/
    tools.py legitimately CONTAINS these words -- they are its denylist --
    and a substring test would flag the guard as the violation."""
    forbidden_modules = ("ibapi", "providers.ibkr_tws_client", "providers.ibkr_tws_options")
    for path in sorted((_SRC / "agents").rglob("*.py")):
        imported = _imports(str(path.relative_to(_SRC)))
        offending = sorted(
            name
            for name in imported
            for prefix in forbidden_modules
            if name == prefix or name.startswith(f"{prefix}.")
        )
        assert not offending, f"{path.name} imports {offending}"
    # And no agent module calls an order method on anything.
    for path in sorted((_SRC / "agents").rglob("*.py")):
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute):
                assert node.attr not in ("placeOrder", "cancelOrder", "exerciseOptions"), (
                    f"{path.name} calls {node.attr}"
                )


# --- requirement 55: one judgement, one verification, no critic chain --


def test_the_graph_has_no_adversarial_roles():
    from agents.graph.workflow import graph_shape

    nodes = graph_shape()["nodes"]
    assert isinstance(nodes, list)
    for forbidden in ("bull", "bear", "critic", "judge", "debate", "adversar"):
        assert not any(forbidden in n for n in nodes), (
            f"a {forbidden!r} node would make this a different methodology"
        )
    # One synthesis, one verification, one bounded revision -- the shape
    # the project already validated.
    assert nodes.count("synthesize") == 1
    assert nodes.count("verify") == 1
    assert nodes.count("revise") == 1
    assert graph_shape()["max_revisions"] == 1


# --- requirement 42/90/91: no reasoning text, no secrets ---------------


def test_no_agent_module_persists_hidden_reasoning_text():
    for module in AGENT_RUNTIME_MODULES:
        text = (_SRC / module).read_text()
        assert "reasoning_content" not in text, (
            f"{module} references the provider's raw reasoning text"
        )


def test_the_graph_state_has_no_field_that_could_hold_a_secret():
    from agents.graph.state import ResearchState

    # Precise names, not substrings: `input_tokens` and `output_tokens`
    # are usage COUNTS and entirely legitimate, so a bare "token" match
    # would flag the honest fields and say nothing about the real risk.
    forbidden = (
        "api_key",
        "apikey",
        "password",
        "secret",
        "credential",
        "authorization",
        "bearer",
        "access_token",
        "private_key",
        "dsn",
    )
    for field_name in ResearchState.__annotations__:
        lowered = field_name.lower()
        for name in forbidden:
            assert name not in lowered, (
                f"ResearchState.{field_name} must not exist (requirement 91)"
            )
    assert "input_tokens" in ResearchState.__annotations__, (
        "usage counts are legitimate state and must not be removed by over-zealous "
        "pattern matching"
    )


def test_a_node_error_message_is_redacted():
    """A provider error can echo a request URL, and this project's adapters
    authenticate via a query parameter."""
    from agents.graph.nodes import _error

    error = _error(
        "synthesize",
        RuntimeError("GET https://api.example.com/v1?apikey=sk-live-abc123 failed"),
        recoverable=True,
    )
    assert "sk-live-abc123" not in error["message"]
    assert "apikey=REDACTED" in error["message"]


# --- requirements 80, 81: the default suite touches nothing real -------


def test_the_default_suite_cannot_reach_the_production_database(db_session):
    """conftest refuses to run if TEST_DATABASE_URL resolves to the real
    one; this asserts the session in hand is genuinely the test database."""
    from core.config import get_settings

    url = str(db_session.get_bind().engine.url)
    assert "5434" in url or "edl-test-db" in url, f"tests are bound to {url}"
    real = get_settings().database_url
    assert url.split("@")[-1] != real.split("@")[-1], (
        "the test session must not point at the application's own database"
    )


def test_the_default_suite_cannot_open_a_live_tws_connection():
    from providers.ibkr_tws_client import TWSConnectionManager

    assert os.environ.get("EDL_ALLOW_LIVE_IBKR") != "1"
    manager = TWSConnectionManager(host="127.0.0.1", port=4001, client_id=1)
    with pytest.raises(AssertionError, match="REAL socket connection"):
        manager.connect()


def test_langsmith_tracing_is_off(monkeypatch):
    """langchain-core pulls langsmith transitively. Tracing would send
    prompts and tool output to a third-party service, so it must be off by
    default and nothing in this codebase may turn it on."""
    from langsmith.utils import tracing_is_enabled

    for var in ("LANGSMITH_TRACING", "LANGCHAIN_TRACING_V2", "LANGSMITH_API_KEY"):
        monkeypatch.delenv(var, raising=False)
    assert tracing_is_enabled() is False
    for path in sorted((_SRC / "agents").rglob("*.py")):
        text = path.read_text()
        assert "LANGSMITH" not in text
        assert "LANGCHAIN_TRACING" not in text
