"""Options Decision Engine V4.3.1 -- Strike Geometry Candidate Sets
(2026-09-03).

V4.3 constructs exactly ONE deterministic geometry per strategy (e.g.
a long call always targets the full expected-move boundary). That is
more economically grounded than V3's ATM-index method, but it is not
yet evidence that one exact normalized strike distance is optimal
under the real T+1 benchmark -- that comparison is V4.4's job, not
built here (this task's own Section 0/14/23).

This module adds a bounded set of economically meaningful ALTERNATIVE
geometries per strategy -- never a blind grid applied uniformly (each
strategy's variants are justified by that strategy's own real payoff
economics, documented per generator below), never fit to the 7 real
settled losses (Section 22), and never scored or ranked (V4.4's job).
V4.3's own base geometry is always included, unmodified, as the
canonical/BASE variant -- this module is purely additive.

CANDIDATE BUDGET (Section 15): at most ``MAX_VARIANTS_PER_STRATEGY``
variants per strategy family, enforced by construction (every
generator below returns a fixed-length tuple, verified by a static
test against this constant) -- never combinatorial explosion.

CONTRACT DEDUPLICATION (Section 16): ``required_unique_contracts`` on
the returned ``StrikeGeometryCandidateSet`` is the deduplicated
(right, strike) set across every variant's legs -- e.g. three long-call
variants sharing no strikes still report 3 contracts, but two credit-
spread wing variants sharing the same short leg report only the wing
strikes as distinct, the short leg once.

TEMPORAL COHERENCE (Section 17): every variant generated by one call
to ``generate_strike_geometry_variants`` shares the SAME
``ExpectedMoveContext`` (one ``observed_at``) and the SAME real
``quotes`` list (one point-in-time snapshot) -- structurally, not by
convention, since every variant generator below receives exactly
those two shared objects and constructs nothing else. This is the
"bounded batch quote strategy" this task's own Section 17 asks for:
one shared snapshot per candidate-set-generation call, deduplicated
contracts requested together, never variant A quoted at T0 and
variant Z quoted minutes later.
"""

from collections.abc import Callable
from dataclasses import dataclass
from decimal import Decimal
from typing import Literal

from analytics.decision.v4_chain_coverage import ChainMetadata
from analytics.decision.v4_compatibility import CONTRADICTION, evaluate_semantic_compatibility
from analytics.decision.v4_expected_move import ExpectedMoveContext
from analytics.decision.v4_market_view import V4MarketView
from analytics.decision.v4_strategy_semantics import get_strategy_semantics
from analytics.decision.v4_strike_engine import (
    STRIKE_ENGINE_VERSION,
    UNCONSTRUCTABLE_IMPLIED_MOVE_REQUIRED,
    UNCONSTRUCTABLE_MISSING_LEG_QUOTE,
    UNCONSTRUCTABLE_ORDERING_VIOLATION,
    V4StrikeSelectionResult,
    build_leg,
    expected_move_boundary_at_fraction,
    fmt_decimal,
    pinning_width_boundary_from_anchor,
    symmetry_error_pct,
    unconstructable_result,
)
from analytics.decision.v4_strike_resolver import Right
from analytics.options.strategy_candidates import StrategyCategory
from providers.types import OptionQuote

GEOMETRY_CANDIDATE_VERSION = "geometry_candidate_v1"

# Section 15's own bound. Every generator below is a fixed-length
# tuple by construction; test_analytics_v4_strike_geometry_variants.py
# verifies no strategy ever exceeds this statically.
MAX_VARIANTS_PER_STRATEGY = 3

FilterMode = Literal["ALL_CANDIDATES", "SEMANTICALLY_PLAUSIBLE_ONLY"]

SKIPPED_SEMANTIC_CONTRADICTION = "SKIPPED_SEMANTIC_CONTRADICTION"


@dataclass(frozen=True)
class StrikeGeometryVariant:
    """One candidate geometry for one strategy. ``result`` reuses
    V4.3's own ``V4StrikeSelectionResult`` unchanged -- legs, target
    rationale, expected-move units, width, symmetry, contract ids, and
    quote diagnostics all already live there (Section 18's own
    per-variant field list), so this module never duplicates that
    shape."""

    variant_id: str
    variant_semantics: str
    result: V4StrikeSelectionResult
    is_base_geometry: bool


@dataclass(frozen=True)
class StrikeGeometryCandidateSet:
    strategy: StrategyCategory
    base_geometry: StrikeGeometryVariant
    variants: tuple[StrikeGeometryVariant, ...]
    required_unique_contracts: tuple[tuple[Right, Decimal], ...]
    coverage_status: str
    chain_metadata_status: str
    candidate_generation_version: str


def _chain_metadata_status_text(chain_metadata: ChainMetadata | None) -> str:
    if chain_metadata is None:
        return "chain_metadata not supplied -- quotes used as-is, provenance not tracked"
    return f"source={chain_metadata.source!r}" + (
        f" (window={chain_metadata.captured_window_size})"
        if chain_metadata.captured_window_size is not None
        else ""
    )


def _dedupe_contracts(
    variants: tuple[StrikeGeometryVariant, ...],
) -> tuple[tuple[Right, Decimal], ...]:
    seen: set[tuple[Right, Decimal]] = set()
    for variant in variants:
        for leg in variant.result.legs:
            if leg.selected_strike is not None:
                seen.add((leg.right, leg.selected_strike))
    return tuple(sorted(seen, key=lambda pair: (pair[0], pair[1])))


def _single_leg_variant(
    category: StrategyCategory,
    action: Literal["buy", "sell"],
    right: Right,
    target_price: Decimal,
    source: str,
    variant_id: str,
    variant_semantics: str,
    context: ExpectedMoveContext,
    quotes: list[OptionQuote],
    *,
    lower_is_this_leg: bool = False,
    upper_is_this_leg: bool = False,
    is_base: bool = False,
) -> StrikeGeometryVariant:
    leg = build_leg(
        action, right, target_price, f"{variant_semantics} ({source}).", quotes, context
    )
    if leg.selected_strike is None:
        result = unconstructable_result(
            category,
            context,
            [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
            f"Real chain has no quoted {right} near the {variant_semantics} target.",
            legs=(leg,),
        )
        return StrikeGeometryVariant(variant_id, variant_semantics, result, is_base)
    result = V4StrikeSelectionResult(
        strategy=category,
        status="constructed",
        spot=context.spot,
        expected_move_context=context,
        legs=(leg,),
        center_target=target_price,
        lower_boundary=leg.selected_strike if lower_is_this_leg else None,
        upper_boundary=leg.selected_strike if upper_is_this_leg else None,
        width=None,
        width_pct_of_spot=None,
        width_in_expected_move_units=leg.expected_move_units,
        symmetry_error_pct=None,
        reason_codes=tuple(dict.fromkeys([source, *leg.reason_codes])),
        explanation=(
            f"{variant_semantics}: target {fmt_decimal(target_price)} ({source}) -> strike "
            f"{leg.selected_strike}."
        ),
        engine_version=STRIKE_ENGINE_VERSION,
    )
    return StrikeGeometryVariant(variant_id, variant_semantics, result, is_base)


def _no_evidence_variant(
    category: StrategyCategory,
    context: ExpectedMoveContext,
    variant_id: str,
    variant_semantics: str,
    is_base: bool = False,
) -> StrikeGeometryVariant:
    """``is_base`` must be threaded through explicitly by every call
    site -- a missing-evidence failure for what WOULD have been the
    base geometry is still the base geometry (every candidate set
    must have exactly one), it just failed to construct."""
    result = unconstructable_result(
        category,
        context,
        [UNCONSTRUCTABLE_IMPLIED_MOVE_REQUIRED],
        "Neither implied move nor adequate historical move data is available for this variant.",
    )
    return StrikeGeometryVariant(variant_id, variant_semantics, result, is_base)


# --------------------------------------------------------------------------
# LONG_CALL / LONG_PUT (Section 8) -- three normalized-EM-unit
# alternatives, economically justified individually (not a blind
# grid): ATM maximizes delta/theta trade-off at the cheapest premium;
# MODEST_OTM is a real, commonly-used middle ground; FULL_EXPECTED_MOVE
# is V4.3's own base (maximum convexity to the move actually
# materializing). Bounded at 3 -- Section 8 does not ask for a 0.25/
# 0.75 EM grid, and adding one would not be economically distinct
# enough from its neighbors to justify the extra contract.
# --------------------------------------------------------------------------

_LONG_OPTION_GRID: tuple[tuple[Decimal, str, str], ...] = (
    (
        Decimal("0"),
        "ATM",
        "At-the-money -- cheapest premium of the three, real linear delta exposure to any "
        "move without requiring the underlying to travel anywhere first.",
    ),
    (
        Decimal("0.5"),
        "MODEST_OTM",
        "Half the expected move -- a real middle ground: more leverage than ATM, less "
        "premium at risk than the full-move target.",
    ),
    (
        Decimal("1"),
        "FULL_EXPECTED_MOVE",
        "The full expected-move boundary -- V4.3's own base geometry, maximum convexity if "
        "the move fully materializes.",
    ),
)


def _long_option_variants(
    category: StrategyCategory, right: Right, side: Literal["up", "down"]
) -> Callable[[ExpectedMoveContext, list[OptionQuote]], tuple[StrikeGeometryVariant, ...]]:
    def _build(
        context: ExpectedMoveContext, quotes: list[OptionQuote]
    ) -> tuple[StrikeGeometryVariant, ...]:
        variants = []
        for fraction, tag, semantics in _LONG_OPTION_GRID:
            variant_id = f"{category.value}_{tag}"
            is_base = fraction == Decimal("1")
            if fraction == 0:
                variants.append(
                    _single_leg_variant(
                        category,
                        "buy",
                        right,
                        context.spot,
                        "ATM_TARGET",
                        variant_id,
                        semantics,
                        context,
                        quotes,
                        lower_is_this_leg=(side == "down"),
                        upper_is_this_leg=(side == "up"),
                        is_base=is_base,
                    )
                )
                continue
            boundary = expected_move_boundary_at_fraction(context, side, fraction)
            if boundary is None:
                variants.append(
                    _no_evidence_variant(category, context, variant_id, semantics, is_base)
                )
                continue
            variants.append(
                _single_leg_variant(
                    category,
                    "buy",
                    right,
                    boundary.price,
                    boundary.source,
                    variant_id,
                    semantics,
                    context,
                    quotes,
                    lower_is_this_leg=(side == "down"),
                    upper_is_this_leg=(side == "up"),
                    is_base=is_base,
                )
            )
        return tuple(variants)

    return _build


_build_long_call_variants = _long_option_variants(StrategyCategory.LONG_CALL, "call", "up")
_build_long_put_variants = _long_option_variants(StrategyCategory.LONG_PUT, "put", "down")


# --------------------------------------------------------------------------
# LONG_STRANGLE (Section 9) -- symmetric distance alternatives. Two
# variants, not four: a strangle's whole economic point is "cheaper
# than a straddle, needs a bigger move" -- HALF_MOVE and FULL_MOVE
# (V4.3's base) already span that real range meaningfully; a third
# point would not represent a materially different economic thesis.
# --------------------------------------------------------------------------

_STRANGLE_GRID: tuple[tuple[Decimal, str, str], ...] = (
    (
        Decimal("0.5"),
        "HALF_MOVE",
        "Half the expected move on each side -- cheaper, more likely to finish ITM on at "
        "least one leg.",
    ),
    (
        Decimal("1"),
        "FULL_MOVE",
        "The full expected-move boundary on each side -- V4.3's own base geometry.",
    ),
)


def _build_long_strangle_variants(
    context: ExpectedMoveContext, quotes: list[OptionQuote]
) -> tuple[StrikeGeometryVariant, ...]:
    variants = []
    for fraction, tag, semantics in _STRANGLE_GRID:
        variant_id = f"long_strangle_{tag}"
        is_base = fraction == Decimal("1")
        call_boundary = expected_move_boundary_at_fraction(context, "up", fraction)
        put_boundary = expected_move_boundary_at_fraction(context, "down", fraction)
        if call_boundary is None or put_boundary is None:
            variants.append(
                _no_evidence_variant(
                    StrategyCategory.LONG_STRANGLE, context, variant_id, semantics, is_base
                )
            )
            continue
        call_leg = build_leg(
            "buy",
            "call",
            call_boundary.price,
            f"{semantics} upper ({call_boundary.source}).",
            quotes,
            context,
        )
        put_leg = build_leg(
            "buy",
            "put",
            put_boundary.price,
            f"{semantics} lower ({put_boundary.source}).",
            quotes,
            context,
        )
        if call_leg.selected_strike is None or put_leg.selected_strike is None:
            result = unconstructable_result(
                StrategyCategory.LONG_STRANGLE,
                context,
                [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                "Real chain lacks a quoted call or put near the target boundary.",
                legs=(call_leg, put_leg),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        if not (put_leg.selected_strike < context.spot < call_leg.selected_strike):
            result = unconstructable_result(
                StrategyCategory.LONG_STRANGLE,
                context,
                [UNCONSTRUCTABLE_ORDERING_VIOLATION],
                f"Resolved put {put_leg.selected_strike} / call {call_leg.selected_strike} "
                f"do not straddle spot {context.spot}.",
                legs=(call_leg, put_leg),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        upper_distance = call_leg.selected_strike - context.spot
        lower_distance = context.spot - put_leg.selected_strike
        width = call_leg.selected_strike - put_leg.selected_strike
        result = V4StrikeSelectionResult(
            strategy=StrategyCategory.LONG_STRANGLE,
            status="constructed",
            spot=context.spot,
            expected_move_context=context,
            legs=(call_leg, put_leg),
            center_target=context.spot,
            lower_boundary=put_leg.selected_strike,
            upper_boundary=call_leg.selected_strike,
            width=width,
            width_pct_of_spot=width / context.spot if context.spot else None,
            width_in_expected_move_units=(
                width / context.implied_move_dollars if context.implied_move_dollars else None
            ),
            symmetry_error_pct=symmetry_error_pct(upper_distance, lower_distance, context.spot),
            reason_codes=tuple(
                dict.fromkeys(
                    [
                        call_boundary.source,
                        put_boundary.source,
                        *call_leg.reason_codes,
                        *put_leg.reason_codes,
                    ]
                )
            ),
            explanation=(
                f"{semantics}: put target {fmt_decimal(put_boundary.price)} -> strike "
                f"{put_leg.selected_strike}; call target {fmt_decimal(call_boundary.price)} -> "
                f"strike {call_leg.selected_strike}."
            ),
            engine_version=STRIKE_ENGINE_VERSION,
        )
        variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
    return tuple(variants)


# --------------------------------------------------------------------------
# Debit spreads (Section 10) -- long leg fixed at ATM (the directional
# anchor, per V4.3's own base rationale) to keep the grid bounded; the
# short leg (which defines the capped profit region) varies between
# the full expected-move target (BASE) and a half-move target (a
# tighter, cheaper spread with a nearer breakeven).
# --------------------------------------------------------------------------


def _debit_spread_variants(
    category: StrategyCategory, right: Right, side: Literal["up", "down"]
) -> Callable[[ExpectedMoveContext, list[OptionQuote]], tuple[StrikeGeometryVariant, ...]]:
    grid = (
        (
            Decimal("0.5"),
            "TIGHT_SHORT",
            "Short leg at half the expected move -- a tighter, cheaper spread with a nearer "
            "breakeven.",
        ),
        (
            Decimal("1"),
            "FULL_MOVE_SHORT",
            "Short leg at the full expected-move target -- V4.3's own base geometry.",
        ),
    )

    def _build(
        context: ExpectedMoveContext, quotes: list[OptionQuote]
    ) -> tuple[StrikeGeometryVariant, ...]:
        variants = []
        for fraction, tag, semantics in grid:
            variant_id = f"{category.value}_{tag}"
            is_base = fraction == Decimal("1")
            boundary = expected_move_boundary_at_fraction(context, side, fraction)
            if boundary is None:
                variants.append(
                    _no_evidence_variant(category, context, variant_id, semantics, is_base)
                )
                continue
            long_leg = build_leg(
                "buy", right, context.spot, "ATM directional anchor.", quotes, context
            )
            short_leg = build_leg(
                "sell", right, boundary.price, f"{semantics} ({boundary.source}).", quotes, context
            )
            if long_leg.selected_strike is None or short_leg.selected_strike is None:
                result = unconstructable_result(
                    category,
                    context,
                    [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                    "Real chain lacks a quoted long or short leg.",
                    legs=(long_leg, short_leg),
                )
                variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
                continue
            ordered = (
                long_leg.selected_strike < short_leg.selected_strike
                if side == "up"
                else long_leg.selected_strike > short_leg.selected_strike
            )
            if not ordered:
                result = unconstructable_result(
                    category,
                    context,
                    [UNCONSTRUCTABLE_ORDERING_VIOLATION],
                    f"Long {long_leg.selected_strike} / short {short_leg.selected_strike} "
                    "produce a zero-width or reversed spread.",
                    legs=(long_leg, short_leg),
                )
                variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
                continue
            width = abs(short_leg.selected_strike - long_leg.selected_strike)
            result = V4StrikeSelectionResult(
                strategy=category,
                status="constructed",
                spot=context.spot,
                expected_move_context=context,
                legs=(long_leg, short_leg),
                center_target=context.spot,
                lower_boundary=min(long_leg.selected_strike, short_leg.selected_strike),
                upper_boundary=max(long_leg.selected_strike, short_leg.selected_strike),
                width=width,
                width_pct_of_spot=width / context.spot if context.spot else None,
                width_in_expected_move_units=(
                    width / context.implied_move_dollars if context.implied_move_dollars else None
                ),
                symmetry_error_pct=None,
                reason_codes=tuple(
                    dict.fromkeys(
                        [boundary.source, *long_leg.reason_codes, *short_leg.reason_codes]
                    )
                ),
                explanation=(
                    f"{semantics}: long ATM {long_leg.selected_strike}; short target "
                    f"{fmt_decimal(boundary.price)} -> strike {short_leg.selected_strike}, "
                    f"width {width}."
                ),
                engine_version=STRIKE_ENGINE_VERSION,
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
        return tuple(variants)

    return _build


_build_bull_call_spread_variants = _debit_spread_variants(
    StrategyCategory.BULL_CALL_SPREAD, "call", "up"
)
_build_bear_put_spread_variants = _debit_spread_variants(
    StrategyCategory.BEAR_PUT_SPREAD, "put", "down"
)


# --------------------------------------------------------------------------
# Credit spreads (Section 11) -- short strike fixed at the full
# adverse-move threshold (V4.2's own directional-threshold semantics
# say the short strike IS the economic thesis; varying it would
# change what view the spread expresses, not just its risk profile).
# The real variation dimension is protective-wing WIDTH: V4.3's own
# minimum-viable next-listed-strike wing (BASE) vs. a wider wing two
# real strikes out where the chain supports it -- real risk/reward
# alternatives V4.4 will eventually be able to compare.
# --------------------------------------------------------------------------


def _nth_strike_beyond(
    quotes: list[OptionQuote],
    right: Right,
    reference: Decimal,
    direction: Literal["up", "down"],
    n: int,
) -> Decimal | None:
    strikes = sorted({q.strike for q in quotes if q.option_type == right})
    if direction == "up":
        beyond = sorted(s for s in strikes if s > reference)
    else:
        beyond = sorted((s for s in strikes if s < reference), reverse=True)
    if len(beyond) < n:
        return None
    return beyond[n - 1]


def _credit_spread_variants(
    category: StrategyCategory, right: Right, side: Literal["up", "down"]
) -> Callable[[ExpectedMoveContext, list[OptionQuote]], tuple[StrikeGeometryVariant, ...]]:
    wing_direction: Literal["up", "down"] = side

    def _build(
        context: ExpectedMoveContext, quotes: list[OptionQuote]
    ) -> tuple[StrikeGeometryVariant, ...]:
        boundary = expected_move_boundary_at_fraction(context, side, Decimal("1"))
        base_id = f"{category.value}_MINIMUM_WING"
        wide_id = f"{category.value}_WIDER_WING"
        if boundary is None:
            return (
                _no_evidence_variant(
                    category, context, base_id, "Minimum-viable protective wing.", True
                ),
                _no_evidence_variant(
                    category,
                    context,
                    wide_id,
                    "Wider protective wing (two real strikes out).",
                    False,
                ),
            )
        short_leg = build_leg(
            "sell",
            right,
            boundary.price,
            f"Adverse-move threshold ({boundary.source}).",
            quotes,
            context,
        )
        if short_leg.selected_strike is None:
            reason = [UNCONSTRUCTABLE_MISSING_LEG_QUOTE]
            explanation = "Real chain lacks a quoted short leg near the adverse-move threshold."
            base_result = unconstructable_result(
                category, context, reason, explanation, legs=(short_leg,)
            )
            wide_result = unconstructable_result(
                category, context, reason, explanation, legs=(short_leg,)
            )
            return (
                StrikeGeometryVariant(
                    base_id, "Minimum-viable protective wing.", base_result, True
                ),
                StrikeGeometryVariant(
                    wide_id, "Wider protective wing (two real strikes out).", wide_result, False
                ),
            )

        variants = []
        for n, variant_id, semantics, is_base in (
            (
                1,
                base_id,
                "Minimum-viable protective wing -- next real listed strike beyond the short.",
                True,
            ),
            (
                2,
                wide_id,
                "Wider protective wing -- two real listed strikes beyond the short.",
                False,
            ),
        ):
            wing_strike = _nth_strike_beyond(
                quotes, right, short_leg.selected_strike, wing_direction, n
            )
            if wing_strike is None:
                result = unconstructable_result(
                    category,
                    context,
                    ["UNCONSTRUCTABLE_NO_PROTECTIVE_WING_AVAILABLE"],
                    f"No real {right} strike exists {n} step(s) beyond the short strike "
                    f"{short_leg.selected_strike}.",
                    legs=(short_leg,),
                )
                variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
                continue
            long_leg = build_leg("buy", right, wing_strike, f"{semantics}", quotes, context)
            if long_leg.selected_strike is None:
                result = unconstructable_result(
                    category,
                    context,
                    [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                    "Real chain lacks a quote at the protective-wing strike.",
                    legs=(short_leg, long_leg),
                )
                variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
                continue
            ordered = (
                long_leg.selected_strike < short_leg.selected_strike
                if side == "down"
                else short_leg.selected_strike < long_leg.selected_strike
            )
            if not ordered:
                result = unconstructable_result(
                    category,
                    context,
                    [UNCONSTRUCTABLE_ORDERING_VIOLATION],
                    f"Protective wing {long_leg.selected_strike} does not lie beyond short "
                    f"strike {short_leg.selected_strike}.",
                    legs=(short_leg, long_leg),
                )
                variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
                continue
            width = abs(short_leg.selected_strike - long_leg.selected_strike)
            result = V4StrikeSelectionResult(
                strategy=category,
                status="constructed",
                spot=context.spot,
                expected_move_context=context,
                legs=(short_leg, long_leg),
                center_target=None,
                lower_boundary=min(long_leg.selected_strike, short_leg.selected_strike),
                upper_boundary=max(long_leg.selected_strike, short_leg.selected_strike),
                width=width,
                width_pct_of_spot=width / context.spot if context.spot else None,
                width_in_expected_move_units=(
                    width / context.implied_move_dollars if context.implied_move_dollars else None
                ),
                symmetry_error_pct=None,
                reason_codes=tuple(
                    dict.fromkeys(
                        [boundary.source, *short_leg.reason_codes, *long_leg.reason_codes]
                    )
                ),
                explanation=(
                    f"{semantics} Short {short_leg.selected_strike}, wing "
                    f"{long_leg.selected_strike}, width {width}."
                ),
                engine_version=STRIKE_ENGINE_VERSION,
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
        return tuple(variants)

    return _build


_build_put_credit_spread_variants = _credit_spread_variants(
    StrategyCategory.PUT_CREDIT_SPREAD, "put", "down"
)
_build_call_credit_spread_variants = _credit_spread_variants(
    StrategyCategory.CALL_CREDIT_SPREAD, "call", "up"
)


# --------------------------------------------------------------------------
# IRON_CONDOR (Section 12) -- short-strike range boundary varies
# between 0.75 EM (a narrower range assumption -- the market moves
# less than fully priced) and 1.0 EM (V4.3's own "sell the expected
# move" base). Bounded at 2: a condor's real economic question is
# "how wide is the profitable range," and these two points already
# represent materially different range theses without inflating the
# candidate count.
# --------------------------------------------------------------------------

_CONDOR_GRID: tuple[tuple[Decimal, str, str], ...] = (
    (
        Decimal("0.75"),
        "NARROWER_RANGE",
        "Short strikes at 75% of the expected move -- a narrower range assumption than the "
        "market's own pricing.",
    ),
    (
        Decimal("1"),
        "FULL_RANGE",
        "Short strikes at the full expected-move boundary -- V4.3's own base geometry, "
        "'selling the expected move'.",
    ),
)


def _build_iron_condor_variants(
    context: ExpectedMoveContext, quotes: list[OptionQuote]
) -> tuple[StrikeGeometryVariant, ...]:
    variants = []
    for fraction, tag, semantics in _CONDOR_GRID:
        variant_id = f"iron_condor_{tag}"
        is_base = fraction == Decimal("1")
        call_boundary = expected_move_boundary_at_fraction(context, "up", fraction)
        put_boundary = expected_move_boundary_at_fraction(context, "down", fraction)
        if call_boundary is None or put_boundary is None:
            variants.append(
                _no_evidence_variant(
                    StrategyCategory.IRON_CONDOR, context, variant_id, semantics, is_base
                )
            )
            continue
        short_put = build_leg(
            "sell",
            "put",
            put_boundary.price,
            f"{semantics} lower boundary ({put_boundary.source}).",
            quotes,
            context,
        )
        short_call = build_leg(
            "sell",
            "call",
            call_boundary.price,
            f"{semantics} upper boundary ({call_boundary.source}).",
            quotes,
            context,
        )
        if short_put.selected_strike is None or short_call.selected_strike is None:
            result = unconstructable_result(
                StrategyCategory.IRON_CONDOR,
                context,
                [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                "Real chain lacks a quoted short put or short call near the range boundary.",
                legs=(short_put, short_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        long_put_strike = _nth_strike_beyond(quotes, "put", short_put.selected_strike, "down", 1)
        long_call_strike = _nth_strike_beyond(quotes, "call", short_call.selected_strike, "up", 1)
        if long_put_strike is None or long_call_strike is None:
            result = unconstructable_result(
                StrategyCategory.IRON_CONDOR,
                context,
                ["UNCONSTRUCTABLE_NO_PROTECTIVE_WING_AVAILABLE"],
                "No further-OTM real strike exists to build one or both protective wings.",
                legs=(short_put, short_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        long_put = build_leg(
            "buy",
            "put",
            long_put_strike,
            "Next real listed strike beyond the short put.",
            quotes,
            context,
        )
        long_call = build_leg(
            "buy",
            "call",
            long_call_strike,
            "Next real listed strike beyond the short call.",
            quotes,
            context,
        )
        if long_put.selected_strike is None or long_call.selected_strike is None:
            result = unconstructable_result(
                StrategyCategory.IRON_CONDOR,
                context,
                [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                "Real chain lacks a quote at one or both protective-wing strikes.",
                legs=(short_put, short_call, long_put, long_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        if not (
            long_put.selected_strike
            < short_put.selected_strike
            < short_call.selected_strike
            < long_call.selected_strike
        ):
            result = unconstructable_result(
                StrategyCategory.IRON_CONDOR,
                context,
                [UNCONSTRUCTABLE_ORDERING_VIOLATION],
                "Resolved strikes do not hold a valid long_put < short_put < short_call < "
                "long_call ordering.",
                legs=(short_put, short_call, long_put, long_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        upper_distance = short_call.selected_strike - context.spot
        lower_distance = context.spot - short_put.selected_strike
        range_width = short_call.selected_strike - short_put.selected_strike
        result = V4StrikeSelectionResult(
            strategy=StrategyCategory.IRON_CONDOR,
            status="constructed",
            spot=context.spot,
            expected_move_context=context,
            legs=(long_put, short_put, short_call, long_call),
            center_target=context.spot,
            lower_boundary=short_put.selected_strike,
            upper_boundary=short_call.selected_strike,
            width=range_width,
            width_pct_of_spot=range_width / context.spot if context.spot else None,
            width_in_expected_move_units=(
                range_width / context.implied_move_dollars if context.implied_move_dollars else None
            ),
            symmetry_error_pct=symmetry_error_pct(upper_distance, lower_distance, context.spot),
            reason_codes=tuple(
                dict.fromkeys(
                    [
                        call_boundary.source,
                        put_boundary.source,
                        *short_put.reason_codes,
                        *short_call.reason_codes,
                        *long_put.reason_codes,
                        *long_call.reason_codes,
                    ]
                )
            ),
            explanation=(
                f"{semantics} Range [{short_put.selected_strike}, {short_call.selected_strike}], "
                f"wings {long_put.selected_strike}/{long_call.selected_strike}."
            ),
            engine_version=STRIKE_ENGINE_VERSION,
        )
        variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
    return tuple(variants)


# --------------------------------------------------------------------------
# Butterfly / iron butterfly (Section 13) -- three named anchors, NEVER
# averaged: NARROW_PIN (historical 25th/75th-percentile move -- only
# offered when the real sample supports quartiles, honestly omitted
# otherwise), BASE_HISTORICAL_RANGE (V4.3's own base, historical
# median), WIDER_RANGE (full implied move). Each is a genuinely
# separate candidate thesis about how wide "small move" really is.
# --------------------------------------------------------------------------


def _build_long_call_butterfly_variants(
    context: ExpectedMoveContext, quotes: list[OptionQuote]
) -> tuple[StrikeGeometryVariant, ...]:
    category = StrategyCategory.LONG_CALL_BUTTERFLY
    anchors: list[tuple[str, str, str]] = []
    if context.historical_quantiles is not None:
        anchors.append(
            (
                "historical_quartile",
                "NARROW_PIN",
                "Historical 25th/75th-percentile move -- a genuinely tighter, "
                "'unsurprising outcome' pin.",
            )
        )
    anchors.append(
        (
            "historical_median",
            "BASE_HISTORICAL_RANGE",
            "Historical median move -- V4.3's own base geometry.",
        )
    )
    anchors.append(
        (
            "implied_move",
            "WIDER_RANGE",
            "Full current implied move -- the market's own (often earnings-inflated) pricing.",
        )
    )

    variants = []
    for anchor, tag, semantics in anchors:
        variant_id = f"{category.value}_{tag}"
        is_base = tag == "BASE_HISTORICAL_RANGE"
        upper = pinning_width_boundary_from_anchor(context, "up", anchor)  # type: ignore[arg-type]
        lower = pinning_width_boundary_from_anchor(context, "down", anchor)  # type: ignore[arg-type]
        if upper is None or lower is None:
            variants.append(_no_evidence_variant(category, context, variant_id, semantics, is_base))
            continue
        # A 1-2-1 call butterfly sells the middle strike at quantity=2.
        center_leg = build_leg(
            "sell",
            "call",
            context.spot,
            "ATM center -- the pinning target.",
            quotes,
            context,
            quantity=2,
        )
        lower_leg = build_leg(
            "buy", "call", lower.price, f"{semantics} lower wing.", quotes, context
        )
        upper_leg = build_leg(
            "buy", "call", upper.price, f"{semantics} upper wing.", quotes, context
        )
        if any(leg.selected_strike is None for leg in (center_leg, lower_leg, upper_leg)):
            result = unconstructable_result(
                category,
                context,
                [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                "Real chain lacks a quoted center or wing leg.",
                legs=(lower_leg, center_leg, upper_leg),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        assert center_leg.selected_strike is not None
        assert lower_leg.selected_strike is not None
        assert upper_leg.selected_strike is not None
        if not (lower_leg.selected_strike < center_leg.selected_strike < upper_leg.selected_strike):
            result = unconstructable_result(
                category,
                context,
                [UNCONSTRUCTABLE_ORDERING_VIOLATION],
                f"Resolved strikes {lower_leg.selected_strike} < {center_leg.selected_strike} "
                f"< {upper_leg.selected_strike} do not hold.",
                legs=(lower_leg, center_leg, upper_leg),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        upper_distance = upper_leg.selected_strike - center_leg.selected_strike
        lower_distance = center_leg.selected_strike - lower_leg.selected_strike
        width = upper_leg.selected_strike - lower_leg.selected_strike
        result = V4StrikeSelectionResult(
            strategy=category,
            status="constructed",
            spot=context.spot,
            expected_move_context=context,
            legs=(lower_leg, center_leg, upper_leg),
            center_target=context.spot,
            lower_boundary=lower_leg.selected_strike,
            upper_boundary=upper_leg.selected_strike,
            width=width,
            width_pct_of_spot=width / context.spot if context.spot else None,
            width_in_expected_move_units=(
                width / context.implied_move_dollars if context.implied_move_dollars else None
            ),
            symmetry_error_pct=symmetry_error_pct(upper_distance, lower_distance, context.spot),
            reason_codes=tuple(
                dict.fromkeys(
                    [
                        upper.source,
                        lower.source,
                        *center_leg.reason_codes,
                        *lower_leg.reason_codes,
                        *upper_leg.reason_codes,
                    ]
                )
            ),
            explanation=(
                f"{semantics} Center {center_leg.selected_strike}, wings "
                f"{lower_leg.selected_strike}/{upper_leg.selected_strike}, width {width}."
            ),
            engine_version=STRIKE_ENGINE_VERSION,
        )
        variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
    return tuple(variants)


def _build_iron_butterfly_variants(
    context: ExpectedMoveContext, quotes: list[OptionQuote]
) -> tuple[StrikeGeometryVariant, ...]:
    category = StrategyCategory.IRON_BUTTERFLY
    anchors: list[tuple[str, str, str]] = []
    if context.historical_quantiles is not None:
        anchors.append(
            (
                "historical_quartile",
                "NARROW_PIN",
                "Historical 25th/75th-percentile move -- a genuinely tighter, "
                "'unsurprising outcome' pin.",
            )
        )
    anchors.append(
        (
            "historical_median",
            "BASE_HISTORICAL_RANGE",
            "Historical median move -- V4.3's own base geometry.",
        )
    )
    anchors.append(
        (
            "implied_move",
            "WIDER_RANGE",
            "Full current implied move -- the market's own (often earnings-inflated) pricing.",
        )
    )

    variants = []
    for anchor, tag, semantics in anchors:
        variant_id = f"iron_butterfly_{tag}"
        is_base = tag == "BASE_HISTORICAL_RANGE"
        upper = pinning_width_boundary_from_anchor(context, "up", anchor)  # type: ignore[arg-type]
        lower = pinning_width_boundary_from_anchor(context, "down", anchor)  # type: ignore[arg-type]
        if upper is None or lower is None:
            variants.append(_no_evidence_variant(category, context, variant_id, semantics, is_base))
            continue
        short_put = build_leg("sell", "put", context.spot, "ATM center (put leg).", quotes, context)
        short_call = build_leg(
            "sell", "call", context.spot, "ATM center (call leg).", quotes, context
        )
        if short_put.selected_strike is None or short_call.selected_strike is None:
            result = unconstructable_result(
                category,
                context,
                [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                "Real chain lacks a quoted ATM put or call.",
                legs=(short_put, short_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        if short_put.selected_strike != short_call.selected_strike:
            result = unconstructable_result(
                category,
                context,
                ["UNCONSTRUCTABLE_SHARED_CENTER_MISMATCH"],
                "Nearest-ATM put and call strikes differ -- cannot honestly support a shared "
                "center at this expiration.",
                legs=(short_put, short_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        center = short_put.selected_strike
        long_put = build_leg("buy", "put", lower.price, f"{semantics} lower wing.", quotes, context)
        long_call = build_leg(
            "buy", "call", upper.price, f"{semantics} upper wing.", quotes, context
        )
        if long_put.selected_strike is None or long_call.selected_strike is None:
            result = unconstructable_result(
                category,
                context,
                [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
                "Real chain lacks a quoted protective wing.",
                legs=(long_put, short_put, short_call, long_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        if not (long_put.selected_strike < center < long_call.selected_strike):
            result = unconstructable_result(
                category,
                context,
                [UNCONSTRUCTABLE_ORDERING_VIOLATION],
                f"Resolved strikes {long_put.selected_strike} < {center} < "
                f"{long_call.selected_strike} do not hold.",
                legs=(long_put, short_put, short_call, long_call),
            )
            variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
            continue
        upper_distance = long_call.selected_strike - center
        lower_distance = center - long_put.selected_strike
        width = long_call.selected_strike - long_put.selected_strike
        result = V4StrikeSelectionResult(
            strategy=category,
            status="constructed",
            spot=context.spot,
            expected_move_context=context,
            legs=(long_put, short_put, short_call, long_call),
            center_target=context.spot,
            lower_boundary=long_put.selected_strike,
            upper_boundary=long_call.selected_strike,
            width=width,
            width_pct_of_spot=width / context.spot if context.spot else None,
            width_in_expected_move_units=(
                width / context.implied_move_dollars if context.implied_move_dollars else None
            ),
            symmetry_error_pct=symmetry_error_pct(upper_distance, lower_distance, context.spot),
            reason_codes=tuple(
                dict.fromkeys(
                    [
                        upper.source,
                        lower.source,
                        *short_put.reason_codes,
                        *short_call.reason_codes,
                        *long_put.reason_codes,
                        *long_call.reason_codes,
                    ]
                )
            ),
            explanation=(
                f"{semantics} Shared center {center}, wings {long_put.selected_strike}/"
                f"{long_call.selected_strike}, width {width}."
            ),
            engine_version=STRIKE_ENGINE_VERSION,
        )
        variants.append(StrikeGeometryVariant(variant_id, semantics, result, is_base))
    return tuple(variants)


# --------------------------------------------------------------------------
# LONG_STRADDLE -- no meaningful variant dimension exists (Section 12's
# own principle applied generally: "only include variants if
# economically justified"). A straddle's whole point is sharing one
# ATM strike; there is no distance parameter to vary without ceasing
# to be a straddle. One variant only, which is also the base.
# --------------------------------------------------------------------------


def _build_long_straddle_variants(
    context: ExpectedMoveContext, quotes: list[OptionQuote]
) -> tuple[StrikeGeometryVariant, ...]:
    semantics = "Nearest coherent-spot strike -- shared by both legs; V4.3's own base geometry."
    target = context.spot
    rationale = (
        "Nearest coherent-spot strike -- shared by both legs of a two-sided convex structure."
    )
    call_leg = build_leg("buy", "call", target, rationale, quotes, context)
    put_leg = build_leg("buy", "put", target, rationale, quotes, context)
    if call_leg.selected_strike is None or put_leg.selected_strike is None:
        result = unconstructable_result(
            StrategyCategory.LONG_STRADDLE,
            context,
            [UNCONSTRUCTABLE_MISSING_LEG_QUOTE],
            "Real chain lacks a quoted call or put near coherent spot.",
            legs=(call_leg, put_leg),
        )
        return (StrikeGeometryVariant("long_straddle_BASE", semantics, result, True),)
    if call_leg.selected_strike != put_leg.selected_strike:
        result = unconstructable_result(
            StrategyCategory.LONG_STRADDLE,
            context,
            ["UNCONSTRUCTABLE_SHARED_CENTER_MISMATCH"],
            f"Nearest-ATM call strike {call_leg.selected_strike} and put strike "
            f"{put_leg.selected_strike} differ.",
            legs=(call_leg, put_leg),
        )
        return (StrikeGeometryVariant("long_straddle_BASE", semantics, result, True),)
    center = call_leg.selected_strike
    result = V4StrikeSelectionResult(
        strategy=StrategyCategory.LONG_STRADDLE,
        status="constructed",
        spot=context.spot,
        expected_move_context=context,
        legs=(call_leg, put_leg),
        center_target=target,
        lower_boundary=None,
        upper_boundary=None,
        width=Decimal(0),
        width_pct_of_spot=Decimal(0),
        width_in_expected_move_units=Decimal(0),
        symmetry_error_pct=Decimal(0),
        reason_codes=tuple(dict.fromkeys([*call_leg.reason_codes, *put_leg.reason_codes])),
        explanation=f"Long straddle centered at real ATM strike {center} (spot {context.spot}).",
        engine_version=STRIKE_ENGINE_VERSION,
    )
    return (StrikeGeometryVariant("long_straddle_BASE", semantics, result, True),)


_VARIANT_GENERATORS: dict[
    StrategyCategory,
    Callable[[ExpectedMoveContext, list[OptionQuote]], tuple[StrikeGeometryVariant, ...]],
] = {
    StrategyCategory.LONG_CALL: _build_long_call_variants,
    StrategyCategory.LONG_PUT: _build_long_put_variants,
    StrategyCategory.BULL_CALL_SPREAD: _build_bull_call_spread_variants,
    StrategyCategory.BEAR_PUT_SPREAD: _build_bear_put_spread_variants,
    StrategyCategory.PUT_CREDIT_SPREAD: _build_put_credit_spread_variants,
    StrategyCategory.CALL_CREDIT_SPREAD: _build_call_credit_spread_variants,
    StrategyCategory.LONG_STRADDLE: _build_long_straddle_variants,
    StrategyCategory.LONG_STRANGLE: _build_long_strangle_variants,
    StrategyCategory.IRON_CONDOR: _build_iron_condor_variants,
    StrategyCategory.LONG_CALL_BUTTERFLY: _build_long_call_butterfly_variants,
    StrategyCategory.IRON_BUTTERFLY: _build_iron_butterfly_variants,
}


def generate_strike_geometry_variants(
    strategy: StrategyCategory,
    context: ExpectedMoveContext,
    quotes: list[OptionQuote],
    *,
    filter_mode: FilterMode = "ALL_CANDIDATES",
    market_view: V4MarketView | None = None,
    chain_metadata: ChainMetadata | None = None,
) -> StrikeGeometryCandidateSet:
    """The one dispatcher every V4.3.1 caller uses. ``filter_mode``
    (Section 19) is diagnostic only -- SEMANTICALLY_PLAUSIBLE_ONLY
    skips variant generation entirely for a strategy V4.2's own
    compatibility engine finds an outright CONTRADICTION for the
    given ``market_view``, never a partial/ranking filter, and never
    the default (ALL_CANDIDATES is). This is NOT the official ranking
    policy (Section 19's own explicit instruction)."""
    if filter_mode == "SEMANTICALLY_PLAUSIBLE_ONLY" and market_view is not None:
        semantics = get_strategy_semantics(strategy)
        compatibility = evaluate_semantic_compatibility(market_view, semantics)
        if compatibility.overall_semantic_compatibility <= CONTRADICTION:
            skipped_result = unconstructable_result(
                strategy,
                context,
                [SKIPPED_SEMANTIC_CONTRADICTION],
                f"Variant generation skipped (SEMANTICALLY_PLAUSIBLE_ONLY): "
                f"{compatibility.explanation}",
            )
            skipped_variant = StrikeGeometryVariant(
                f"{strategy.value}_SKIPPED",
                "Skipped: outright V4.2 semantic contradiction.",
                skipped_result,
                True,
            )
            return StrikeGeometryCandidateSet(
                strategy=strategy,
                base_geometry=skipped_variant,
                variants=(skipped_variant,),
                required_unique_contracts=(),
                coverage_status="0/0 constructed (filtered: semantic contradiction)",
                chain_metadata_status=_chain_metadata_status_text(chain_metadata),
                candidate_generation_version=GEOMETRY_CANDIDATE_VERSION,
            )

    variants = _VARIANT_GENERATORS[strategy](context, quotes)
    base_geometry = next(v for v in variants if v.is_base_geometry)
    constructed = sum(1 for v in variants if v.result.status == "constructed")
    return StrikeGeometryCandidateSet(
        strategy=strategy,
        base_geometry=base_geometry,
        variants=variants,
        required_unique_contracts=_dedupe_contracts(variants),
        coverage_status=f"{constructed}/{len(variants)} constructed",
        chain_metadata_status=_chain_metadata_status_text(chain_metadata),
        candidate_generation_version=GEOMETRY_CANDIDATE_VERSION,
    )


def generate_all_strategy_variant_sets(
    context: ExpectedMoveContext,
    quotes: list[OptionQuote],
    *,
    chain_metadata: ChainMetadata | None = None,
) -> dict[StrategyCategory, StrikeGeometryCandidateSet]:
    """Convenience function for the Section 15 candidate-count budget
    demonstration -- generates every strategy's variant set against
    one shared context/quotes (one point-in-time snapshot, Section
    17). Never used by any official pipeline; diagnostic only."""
    return {
        strategy: generate_strike_geometry_variants(
            strategy, context, quotes, chain_metadata=chain_metadata
        )
        for strategy in StrategyCategory
    }
