import { api } from "../../../api/client";
import { useAsync } from "../../../hooks/useAsync";
import { formatRelativeTime } from "../../../lib/format";
import { fmtMarketCap } from "../../v4/shared";
import { LifecyclePill, MarketDataQualityBadge, Metric, SectionHeader, Timestamp } from "../../v4/ui";
import type { ResearchOverview } from "../../../types/api";

// Company Overview (V4-only reset, 2026-09-02): where this company stands
// for the V4 forward test -- research readiness (Company + fresh AI thesis,
// the same rule the 15:30 ET decision gate applies), the next earnings
// event, and the latest V4 decision. Nothing here refers to a retired
// control cohort.

const THESIS_FRESHNESS_DAYS = 7;

export function OverviewV4Tab({ overview, onGo }: { overview: ResearchOverview; onGo: (tab: string) => void }) {
  const ticker = overview.ticker;
  const v4 = useAsync(() => api.getV4ShadowDecisions({ ticker, limit: 1 }), [ticker]);
  const theses = useAsync(() => api.getThesisHistory(ticker, { limit: 1 }), [ticker]);
  const calendar = useAsync(() => api.getSymbolEarningsCalendar(ticker), [ticker]);
  const cfgs = useAsync(
    () => (v4.data?.decisions[0] ? api.getV4ShadowConfigurations(v4.data.decisions[0].id) : Promise.resolve(null)),
    [v4.data?.decisions[0]?.id],
  );
  const c = overview.company;
  const om = overview.options_market;
  const latestV4 = v4.data?.decisions[0] ?? null;
  const latestThesis = theses.data?.[0] ?? null;
  const thesisAgeDays = latestThesis ? (Date.now() - new Date(latestThesis.created_at).getTime()) / 86_400_000 : null;
  const thesisFresh = thesisAgeDays !== null && thesisAgeDays < THESIS_FRESHNESS_DAYS;
  const researchPrepared = !!overview.latest_job && overview.latest_job.status !== "failed" && overview.filings_count > 0;
  const v4Ready = !!c && thesisFresh;
  const defaultCfg = cfgs.data?.configurations.find((x) => x.configuration_key === cfgs.data?.default_configuration_key) ?? null;
  const today = new Date().toISOString().slice(0, 10);
  const nextEvent = (calendar.data ?? []).filter((e) => e.earnings_date >= today).sort((a, b) => a.earnings_date.localeCompare(b.earnings_date))[0] ?? (calendar.data ?? [])[0] ?? null;

  return (
    <div>
      <div className="card" data-testid="overview-summary">
        <SectionHeader title={c?.name ?? ticker} eyebrow="Company" right={<span className="mono">{ticker}</span>} />
        <div className="grid grid-4" style={{ gap: 10 }}>
          <Metric label="Market cap" value={fmtMarketCap(nextEvent?.market_cap)} mono />
          <Metric label="Next earnings" value={nextEvent?.earnings_date ?? "—"} mono sub={nextEvent ? `${nextEvent.earnings_time.toUpperCase()} · ${nextEvent.source}` : "no calendar event"} />
          <Metric label="Market data" value={<MarketDataQualityBadge quality={om?.market_data_quality ?? null} />} />
          <Metric label="V4 windows" value="15:30 ET" mono sub="entry on the legal day · settlement 15:30 ET on the first post-earnings trading day" />
        </div>
        <div className="grid grid-4" style={{ gap: 10, marginTop: 10 }}>
          <Metric label="Research" value={<span className={researchPrepared ? "pill pill-positive" : "pill pill-warning"}>{researchPrepared ? "prepared" : "not prepared"}</span>}
            sub={overview.latest_job?.completed_at ? `prepared ${formatRelativeTime(overview.latest_job.completed_at)}` : "not prepared yet"} />
          <Metric label="AI thesis" value={latestThesis ? <span className={thesisFresh ? "pill pill-positive" : "pill pill-warning"}>{thesisFresh ? "fresh" : "stale"}</span> : <span className="pill pill-neutral">none</span>}
            sub={latestThesis ? `${Math.floor(thesisAgeDays ?? 0)}d old · ${latestThesis.model}` : "generated by the nightly research preparation"} />
          <Metric label="V4 readiness" value={v4Ready ? <span className="pill pill-positive" data-testid="v4-ready">ready</span> : <span className="pill pill-warning" data-testid="v4-ready">not ready</span>}
            sub={v4Ready ? "passes the 15:30 ET research gate" : !c ? "no company record yet" : "needs a fresh AI thesis (< 7 days)"} />
          <Metric label="Latest V4 decision" value={latestV4 ? <LifecyclePill lifecycle={defaultCfg?.lifecycle ?? latestV4.status} /> : <span className="pill pill-neutral">none yet</span>}
            sub={latestV4 ? <Timestamp iso={latestV4.legal_decision_window_at} /> : "V4 has not observed this company"} />
        </div>
      </div>

      <div className="card">
        <SectionHeader title="Go deeper" />
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          <button className="btn-secondary" onClick={() => onGo("setup")}>Timing &amp; expected move →</button>
          <button className="btn-secondary" onClick={() => onGo("research")}>AI thesis →</button>
          <button className="btn-secondary" onClick={() => onGo("view")}>Direction &amp; confidence →</button>
          <button className="btn-secondary" onClick={() => onGo("decision")}>Six-config recommendation →</button>
          <button className="btn-secondary" onClick={() => onGo("candidates")}>Explore frozen structures →</button>
          <button className="btn-secondary" onClick={() => onGo("outcome")}>Entry &amp; settlement →</button>
        </div>
      </div>
    </div>
  );
}
