"""add ai_extraction table

Revision ID: 008aae083f49
Revises: 74c62fe04b0b
Create Date: 2026-08-17 02:40:30.757369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008aae083f49'
down_revision: Union[str, Sequence[str], None] = '74c62fe04b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('extraction_type', sa.String(length=64), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extraction_company_id'), 'ai_extraction', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_extraction_extraction_type'), 'ai_extraction', ['extraction_type'], unique=False)
    op.create_index(op.f('ix_ai_extraction_filing_id'), 'ai_extraction', ['filing_id'], unique=False)
    # NOTE: autogenerate wrongly proposed dropping ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts here — those were created via raw op.execute()
    # in the previous migration (not SQLAlchemy ORM metadata), so autogenerate's
    # model-vs-DB diff sees them as "not declared" and wants to remove them. They
    # are real, load-bearing indexes (see 74c62fe04b0b) and are intentionally left
    # alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (the corresponding erroneous create_index calls for the hnsw/fts
    # indexes were removed from upgrade() above, so nothing to re-add here)
    op.drop_index(op.f('ix_ai_extraction_filing_id'), table_name='ai_extraction')
    op.drop_index(op.f('ix_ai_extraction_extraction_type'), table_name='ai_extraction')
    op.drop_index(op.f('ix_ai_extraction_company_id'), table_name='ai_extraction')
    op.drop_table('ai_extraction')
    # ### end Alembic commands ###
