"""add market_data_quality and external_contract_id to options_snapshot

Revision ID: 0e4a99eca9fb
Revises: 1c951fc14f9f
Create Date: 2026-08-17 22:08:31.115579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4a99eca9fb'
down_revision: Union[str, Sequence[str], None] = '1c951fc14f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate wants to drop ix_document_chunk_embedding_hnsw and
    # ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # autogenerate can't see as ORM-managed. Manually stripped; see prior
    # migrations.
    market_data_quality_enum = sa.Enum(
        'LIVE', 'DELAYED', 'FROZEN', 'UNKNOWN', name='market_data_quality'
    )
    market_data_quality_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'options_snapshot',
        sa.Column('market_data_quality', market_data_quality_enum, nullable=True),
    )
    op.add_column('options_snapshot', sa.Column('external_contract_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options_snapshot', 'external_contract_id')
    op.drop_column('options_snapshot', 'market_data_quality')
    sa.Enum(name='market_data_quality').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
