"""add budget-aware fields to ai_decision_version

Revision ID: 0e6cd12c8226
Revises: 261953c77cda
Create Date: 2026-08-19 05:14:21.451706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6cd12c8226'
down_revision: Union[str, Sequence[str], None] = '261953c77cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also wants to drop ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # autogenerate can't see as ORM-managed. Manually stripped; see prior
    # migrations (e.g. f9282e8f03a4).
    op.add_column('ai_decision_version', sa.Column('trade_budget', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('ai_decision_version', sa.Column('risk_cap', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('ai_decision_version', sa.Column('risk_cap_is_percent', sa.Boolean(), nullable=True))
    op.add_column('ai_decision_version', sa.Column('recommended_quantity', sa.Integer(), nullable=True))
    op.add_column('ai_decision_version', sa.Column('recommended_capital_at_risk', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('ai_decision_version', sa.Column('budget_infeasible_minimum', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_decision_version', 'budget_infeasible_minimum')
    op.drop_column('ai_decision_version', 'recommended_capital_at_risk')
    op.drop_column('ai_decision_version', 'recommended_quantity')
    op.drop_column('ai_decision_version', 'risk_cap_is_percent')
    op.drop_column('ai_decision_version', 'risk_cap')
    op.drop_column('ai_decision_version', 'trade_budget')
    # ### end Alembic commands ###
