"""add strategy_replay table

Revision ID: 0ff4843a4926
Revises: 6ca22393cc76
Create Date: 2026-08-17 02:06:34.501964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff4843a4926'
down_revision: Union[str, Sequence[str], None] = '6ca22393cc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_replay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('strike_selection_rule', sa.String(length=64), nullable=False),
    sa.Column('entry_snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.Column('net_premium', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('underlying_price_at_entry', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('max_profit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('breakevens', sa.JSON(), nullable=False),
    sa.Column('underlying_price_at_evaluation', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('payoff_at_evaluation', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_replay_earnings_event_id'), 'strategy_replay', ['earnings_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_replay_earnings_event_id'), table_name='strategy_replay')
    op.drop_table('strategy_replay')
    # ### end Alembic commands ###
