"""add target_earnings_date to volatility_snapshot

Revision ID: 1c951fc14f9f
Revises: dd02627a107f
Create Date: 2026-08-17 18:14:30.974487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c951fc14f9f'
down_revision: Union[str, Sequence[str], None] = 'dd02627a107f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate wants to drop ix_document_chunk_embedding_hnsw and
    # ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # autogenerate can't see as ORM-managed. Manually stripped; see prior
    # migrations.
    op.add_column('volatility_snapshot', sa.Column('target_earnings_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_volatility_snapshot_target_earnings_date'), 'volatility_snapshot', ['target_earnings_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volatility_snapshot_target_earnings_date'), table_name='volatility_snapshot')
    op.drop_column('volatility_snapshot', 'target_earnings_date')
    # ### end Alembic commands ###
