"""add provider credential, provider usage event, options snapshot purpose

Revision ID: 261953c77cda
Revises: e435021adcc4
Create Date: 2026-08-19 03:48:06.560750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261953c77cda'
down_revision: Union[str, Sequence[str], None] = 'e435021adcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also wants to drop ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # autogenerate can't see as ORM-managed. Manually stripped; see prior
    # migrations (e.g. f9282e8f03a4).
    op.create_table('provider_credential',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('secret_last4', sa.String(length=8), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('provider_usage_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.String(length=32), nullable=True),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_units', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_usage_event_domain'), 'provider_usage_event', ['domain'], unique=False)
    op.create_index(op.f('ix_provider_usage_event_occurred_at'), 'provider_usage_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_provider_usage_event_provider'), 'provider_usage_event', ['provider'], unique=False)
    # op.add_column doesn't issue CREATE TYPE for an inline sa.Enum() on an
    # existing table (unlike op.create_table) -- create it explicitly first,
    # matching b83185a6afdb's precedent for options_snapshot_anchor.
    purpose_enum = sa.Enum('INTRADAY', 'CLOSE', 'MANUAL', 'EARNINGS', name='options_snapshot_purpose')
    purpose_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'options_snapshot',
        sa.Column(
            'purpose',
            sa.Enum('INTRADAY', 'CLOSE', 'MANUAL', 'EARNINGS', name='options_snapshot_purpose', create_type=False),
            server_default='INTRADAY',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options_snapshot', 'purpose')
    sa.Enum(name='options_snapshot_purpose').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_provider_usage_event_provider'), table_name='provider_usage_event')
    op.drop_index(op.f('ix_provider_usage_event_occurred_at'), table_name='provider_usage_event')
    op.drop_index(op.f('ix_provider_usage_event_domain'), table_name='provider_usage_event')
    op.drop_table('provider_usage_event')
    op.drop_table('provider_credential')
    # ### end Alembic commands ###
