"""add price_bar table and earnings_event period_end_date

Revision ID: 6ca22393cc76
Revises: c535e22e3a6d
Create Date: 2026-08-17 01:17:00.426449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca22393cc76'
down_revision: Union[str, Sequence[str], None] = 'c535e22e3a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', 'source_provider', name='uq_price_bar')
    )
    op.create_index(op.f('ix_price_bar_company_id'), 'price_bar', ['company_id'], unique=False)
    op.create_index(op.f('ix_price_bar_ticker'), 'price_bar', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_bar_trade_date'), 'price_bar', ['trade_date'], unique=False)
    op.add_column('earnings_event', sa.Column('period_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_event', 'period_end_date')
    op.drop_index(op.f('ix_price_bar_trade_date'), table_name='price_bar')
    op.drop_index(op.f('ix_price_bar_ticker'), table_name='price_bar')
    op.drop_index(op.f('ix_price_bar_company_id'), table_name='price_bar')
    op.drop_table('price_bar')
    # ### end Alembic commands ###
