"""add document_chunk table with pgvector embeddings

Revision ID: 74c62fe04b0b
Revises: 0ff4843a4926
Create Date: 2026-08-17 02:24:12.473245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '74c62fe04b0b'
down_revision: Union[str, Sequence[str], None] = '0ff4843a4926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=256), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'chunk_index', name='uq_document_chunk')
    )
    op.create_index(op.f('ix_document_chunk_company_id'), 'document_chunk', ['company_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_filing_id'), 'document_chunk', ['filing_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_document_chunk_embedding_hnsw ON document_chunk "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_document_chunk_text_fts ON document_chunk "
        "USING gin (to_tsvector('english', text))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunk_filing_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_company_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
