"""add portfolio_position_snapshot table

Revision ID: 75655667cae0
Revises: 0e4a99eca9fb
Create Date: 2026-08-17 22:32:14.806428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75655667cae0'
down_revision: Union[str, Sequence[str], None] = '0e4a99eca9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_position_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id_masked', sa.String(length=16), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('contract_description', sa.String(length=128), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('option_expiry', sa.String(length=16), nullable=True),
    sa.Column('option_right', sa.String(length=1), nullable=True),
    sa.Column('option_strike', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id_masked', 'snapshot_timestamp', 'conid', name='uq_portfolio_position_snapshot')
    )
    op.create_index(op.f('ix_portfolio_position_snapshot_account_id_masked'), 'portfolio_position_snapshot', ['account_id_masked'], unique=False)
    op.create_index(op.f('ix_portfolio_position_snapshot_conid'), 'portfolio_position_snapshot', ['conid'], unique=False)
    op.create_index(op.f('ix_portfolio_position_snapshot_snapshot_timestamp'), 'portfolio_position_snapshot', ['snapshot_timestamp'], unique=False)
    # NOTE: autogenerate also wants to drop ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # autogenerate can't see as ORM-managed. Manually stripped; see prior
    # migrations.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_position_snapshot_snapshot_timestamp'), table_name='portfolio_position_snapshot')
    op.drop_index(op.f('ix_portfolio_position_snapshot_conid'), table_name='portfolio_position_snapshot')
    op.drop_index(op.f('ix_portfolio_position_snapshot_account_id_masked'), table_name='portfolio_position_snapshot')
    op.drop_table('portfolio_position_snapshot')
    # ### end Alembic commands ###
