"""add earnings_estimate_snapshot table

Revision ID: 81cec62d0ba7
Revises: 008aae083f49
Create Date: 2026-08-17 17:39:31.237882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cec62d0ba7'
down_revision: Union[str, Sequence[str], None] = '008aae083f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_estimate_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_period_end_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eps_estimate_average', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_estimate_high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_estimate_low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_estimate_analyst_count', sa.Integer(), nullable=True),
    sa.Column('eps_estimate_revision_up_30d', sa.Integer(), nullable=True),
    sa.Column('eps_estimate_revision_down_30d', sa.Integer(), nullable=True),
    sa.Column('eps_revision_direction', sa.Enum('UP', 'DOWN', 'FLAT', 'UNKNOWN', name='eps_revision_direction'), nullable=False),
    sa.Column('revenue_estimate_average', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_estimate_high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_estimate_low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_estimate_analyst_count', sa.Integer(), nullable=True),
    sa.Column('revenue_revision_direction', sa.Enum('UP', 'DOWN', 'FLAT', 'UNKNOWN', name='revenue_revision_direction'), nullable=False),
    sa.Column('estimated_report_date', sa.Date(), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_period_end_date', 'snapshot_timestamp', name='uq_earnings_estimate_snapshot')
    )
    op.create_index(op.f('ix_earnings_estimate_snapshot_company_id'), 'earnings_estimate_snapshot', ['company_id'], unique=False)
    op.create_index(op.f('ix_earnings_estimate_snapshot_fiscal_period_end_date'), 'earnings_estimate_snapshot', ['fiscal_period_end_date'], unique=False)
    op.create_index(op.f('ix_earnings_estimate_snapshot_snapshot_timestamp'), 'earnings_estimate_snapshot', ['snapshot_timestamp'], unique=False)
    # NOTE: autogenerate wanted to also drop ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts here -- the same recurring false
    # positive documented for the 74c62fe04b0b and 008aae083f49 migrations
    # (autogenerate doesn't understand indexes created via raw op.execute()
    # SQL in an earlier migration). Removed manually; those indexes are
    # untouched by this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_estimate_snapshot_snapshot_timestamp'), table_name='earnings_estimate_snapshot')
    op.drop_index(op.f('ix_earnings_estimate_snapshot_fiscal_period_end_date'), table_name='earnings_estimate_snapshot')
    op.drop_index(op.f('ix_earnings_estimate_snapshot_company_id'), table_name='earnings_estimate_snapshot')
    op.drop_table('earnings_estimate_snapshot')
    # ### end Alembic commands ###
