"""add v4 shadow evidence tables

Revision ID: 81fc71b9cc96
Revises: f381a1bde880
Create Date: 2026-09-01 18:40:38.750080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81fc71b9cc96'
down_revision: Union[str, Sequence[str], None] = 'f381a1bde880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v4_shadow_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_calendar_event_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_decision_window_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_input_skew_seconds', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('no_action_reason', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=48), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('view_direction', sa.String(length=16), nullable=True),
    sa.Column('view_volatility', sa.String(length=24), nullable=True),
    sa.Column('view_expected_move_intent', sa.String(length=24), nullable=True),
    sa.Column('view_confidence', sa.String(length=24), nullable=True),
    sa.Column('view_reasoning', sa.Text(), nullable=True),
    sa.Column('view_evidence_refs', sa.JSON(), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('decision_view_schema_version', sa.String(length=48), nullable=True),
    sa.Column('underlying_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('underlying_quote_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_data_quality', sa.String(length=24), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.Column('shadow_schema_version', sa.String(length=48), nullable=False),
    sa.Column('strategy_semantics_version', sa.String(length=48), nullable=True),
    sa.Column('compatibility_version', sa.String(length=48), nullable=True),
    sa.Column('expected_move_version', sa.String(length=48), nullable=True),
    sa.Column('strike_engine_version', sa.String(length=48), nullable=True),
    sa.Column('geometry_version', sa.String(length=48), nullable=True),
    sa.Column('valuation_version', sa.String(length=48), nullable=True),
    sa.Column('scenario_grid_version', sa.String(length=64), nullable=True),
    sa.Column('iv_scenario_version', sa.String(length=48), nullable=True),
    sa.Column('ranking_version', sa.String(length=64), nullable=True),
    sa.Column('rank_1_candidate_id', sa.String(length=128), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('rankable_candidate_count', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('candidate_generation_ms', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('valuation_ms', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('ranking_ms', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('tws_request_count', sa.Integer(), nullable=True),
    sa.Column('unique_contracts_quoted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earnings_calendar_event_id'], ['earnings_calendar_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('earnings_calendar_event_id', 'legal_decision_window_at', 'engine_version', name='uq_v4_shadow_decision_event_window_engine')
    )
    op.create_index(op.f('ix_v4_shadow_decision_earnings_calendar_event_id'), 'v4_shadow_decision', ['earnings_calendar_event_id'], unique=False)
    op.create_index(op.f('ix_v4_shadow_decision_failure_category'), 'v4_shadow_decision', ['failure_category'], unique=False)
    op.create_index(op.f('ix_v4_shadow_decision_legal_decision_window_at'), 'v4_shadow_decision', ['legal_decision_window_at'], unique=False)
    op.create_index(op.f('ix_v4_shadow_decision_status'), 'v4_shadow_decision', ['status'], unique=False)
    op.create_index('ix_v4_shadow_decision_status_window', 'v4_shadow_decision', ['status', 'legal_decision_window_at'], unique=False)
    op.create_index(op.f('ix_v4_shadow_decision_ticker'), 'v4_shadow_decision', ['ticker'], unique=False)
    op.create_table('v4_shadow_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadow_decision_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=48), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('geometry_variant_id', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('validity_status', sa.String(length=48), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('semantic_compatibility', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('semantic_tier', sa.String(length=24), nullable=True),
    sa.Column('semantic_reason_codes', sa.JSON(), nullable=True),
    sa.Column('core_worst_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('core_median_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('core_best_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('core_positive_scenario_fraction', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('core_positive_region_count', sa.Integer(), nullable=True),
    sa.Column('core_region_count', sa.Integer(), nullable=True),
    sa.Column('core_scenario_average_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('core_scenarios_valued', sa.Integer(), nullable=True),
    sa.Column('no_profitable_region', sa.Boolean(), nullable=True),
    sa.Column('profit_concentrated_in_single_region', sa.Boolean(), nullable=True),
    sa.Column('stress_worst_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stress_large_move_survival', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stress_vs_core_worst_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stress_scenarios_valued', sa.Integer(), nullable=True),
    sa.Column('mean_relative_spread', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('worst_relative_spread', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('two_sided_leg_count', sa.Integer(), nullable=True),
    sa.Column('leg_count', sa.Integer(), nullable=True),
    sa.Column('required_sides_complete', sa.Boolean(), nullable=True),
    sa.Column('max_leg_timestamp_skew_seconds', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('earliest_leg_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_leg_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_data_quality', sa.String(length=48), nullable=True),
    sa.Column('standardized_capital', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('entry_cash_required', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('capital_utilisation', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ranking_key', sa.JSON(), nullable=True),
    sa.Column('rank_explanation', sa.Text(), nullable=True),
    sa.Column('data_quality_warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shadow_decision_id'], ['v4_shadow_decision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shadow_decision_id', 'candidate_id', name='uq_v4_shadow_candidate_identity')
    )
    op.create_index(op.f('ix_v4_shadow_candidate_rank'), 'v4_shadow_candidate', ['rank'], unique=False)
    op.create_index(op.f('ix_v4_shadow_candidate_shadow_decision_id'), 'v4_shadow_candidate', ['shadow_decision_id'], unique=False)
    op.create_index(op.f('ix_v4_shadow_candidate_validity_status'), 'v4_shadow_candidate', ['validity_status'], unique=False)
    op.create_table('v4_shadow_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadow_decision_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failure_category', sa.String(length=48), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('net_executable_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_data_quality', sa.String(length=48), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=True),
    sa.Column('max_leg_timestamp_skew_seconds', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('legs_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shadow_decision_id'], ['v4_shadow_decision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shadow_decision_id', 'phase', name='uq_v4_shadow_observation_one_per_phase')
    )
    op.create_index(op.f('ix_v4_shadow_observation_phase'), 'v4_shadow_observation', ['phase'], unique=False)
    op.create_index(op.f('ix_v4_shadow_observation_shadow_decision_id'), 'v4_shadow_observation', ['shadow_decision_id'], unique=False)
    op.create_index(op.f('ix_v4_shadow_observation_status'), 'v4_shadow_observation', ['status'], unique=False)
    op.create_table('v4_shadow_run_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadow_decision_id', sa.Integer(), nullable=True),
    sa.Column('earnings_calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earnings_calendar_event_id'], ['earnings_calendar_event.id'], ),
    sa.ForeignKeyConstraint(['shadow_decision_id'], ['v4_shadow_decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v4_shadow_run_event_category'), 'v4_shadow_run_event', ['category'], unique=False)
    op.create_index(op.f('ix_v4_shadow_run_event_earnings_calendar_event_id'), 'v4_shadow_run_event', ['earnings_calendar_event_id'], unique=False)
    op.create_index(op.f('ix_v4_shadow_run_event_shadow_decision_id'), 'v4_shadow_run_event', ['shadow_decision_id'], unique=False)
    op.create_index(op.f('ix_v4_shadow_run_event_stage'), 'v4_shadow_run_event', ['stage'], unique=False)
    op.create_table('v4_shadow_settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadow_decision_id', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failure_category', sa.String(length=48), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('entry_net_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_net_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('return_on_standardized_capital', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_data_quality', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shadow_decision_id'], ['v4_shadow_decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v4_shadow_settlement_shadow_decision_id'), 'v4_shadow_settlement', ['shadow_decision_id'], unique=True)
    op.create_index(op.f('ix_v4_shadow_settlement_status'), 'v4_shadow_settlement', ['status'], unique=False)
    op.create_table('v4_shadow_candidate_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadow_candidate_id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('right', sa.String(length=8), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('external_contract_id', sa.String(length=32), nullable=True),
    sa.Column('required_side', sa.String(length=8), nullable=True),
    sa.Column('required_side_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('market_data_quality', sa.String(length=24), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quote_age_seconds', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shadow_candidate_id'], ['v4_shadow_candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shadow_candidate_id', 'leg_index', name='uq_v4_shadow_leg_index')
    )
    op.create_index(op.f('ix_v4_shadow_candidate_leg_shadow_candidate_id'), 'v4_shadow_candidate_leg', ['shadow_candidate_id'], unique=False)

    # Section 8 -- append-only evidence. Reuses the SAME
    # reject_snapshot_update() trigger function every official V3
    # evidence table already installs; shadow rows are written once,
    # fully formed, and never updated. Retry history is appended to
    # v4_shadow_run_event instead of mutating a frozen decision.
    op.execute(
        """
        CREATE TRIGGER v4_shadow_decision_no_update
        BEFORE UPDATE ON v4_shadow_decision
        FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER v4_shadow_candidate_no_update
        BEFORE UPDATE ON v4_shadow_candidate
        FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER v4_shadow_candidate_leg_no_update
        BEFORE UPDATE ON v4_shadow_candidate_leg
        FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER v4_shadow_observation_no_update
        BEFORE UPDATE ON v4_shadow_observation
        FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER v4_shadow_settlement_no_update
        BEFORE UPDATE ON v4_shadow_settlement
        FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER v4_shadow_run_event_no_update
        BEFORE UPDATE ON v4_shadow_run_event
        FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS v4_shadow_decision_no_update ON v4_shadow_decision")
    op.execute("DROP TRIGGER IF EXISTS v4_shadow_candidate_no_update ON v4_shadow_candidate")
    op.execute("DROP TRIGGER IF EXISTS v4_shadow_candidate_leg_no_update ON v4_shadow_candidate_leg")
    op.execute("DROP TRIGGER IF EXISTS v4_shadow_observation_no_update ON v4_shadow_observation")
    op.execute("DROP TRIGGER IF EXISTS v4_shadow_settlement_no_update ON v4_shadow_settlement")
    op.execute("DROP TRIGGER IF EXISTS v4_shadow_run_event_no_update ON v4_shadow_run_event")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v4_shadow_candidate_leg_shadow_candidate_id'), table_name='v4_shadow_candidate_leg')
    op.drop_table('v4_shadow_candidate_leg')
    op.drop_index(op.f('ix_v4_shadow_settlement_status'), table_name='v4_shadow_settlement')
    op.drop_index(op.f('ix_v4_shadow_settlement_shadow_decision_id'), table_name='v4_shadow_settlement')
    op.drop_table('v4_shadow_settlement')
    op.drop_index(op.f('ix_v4_shadow_run_event_stage'), table_name='v4_shadow_run_event')
    op.drop_index(op.f('ix_v4_shadow_run_event_shadow_decision_id'), table_name='v4_shadow_run_event')
    op.drop_index(op.f('ix_v4_shadow_run_event_earnings_calendar_event_id'), table_name='v4_shadow_run_event')
    op.drop_index(op.f('ix_v4_shadow_run_event_category'), table_name='v4_shadow_run_event')
    op.drop_table('v4_shadow_run_event')
    op.drop_index(op.f('ix_v4_shadow_observation_status'), table_name='v4_shadow_observation')
    op.drop_index(op.f('ix_v4_shadow_observation_shadow_decision_id'), table_name='v4_shadow_observation')
    op.drop_index(op.f('ix_v4_shadow_observation_phase'), table_name='v4_shadow_observation')
    op.drop_table('v4_shadow_observation')
    op.drop_index(op.f('ix_v4_shadow_candidate_validity_status'), table_name='v4_shadow_candidate')
    op.drop_index(op.f('ix_v4_shadow_candidate_shadow_decision_id'), table_name='v4_shadow_candidate')
    op.drop_index(op.f('ix_v4_shadow_candidate_rank'), table_name='v4_shadow_candidate')
    op.drop_table('v4_shadow_candidate')
    op.drop_index(op.f('ix_v4_shadow_decision_ticker'), table_name='v4_shadow_decision')
    op.drop_index('ix_v4_shadow_decision_status_window', table_name='v4_shadow_decision')
    op.drop_index(op.f('ix_v4_shadow_decision_status'), table_name='v4_shadow_decision')
    op.drop_index(op.f('ix_v4_shadow_decision_legal_decision_window_at'), table_name='v4_shadow_decision')
    op.drop_index(op.f('ix_v4_shadow_decision_failure_category'), table_name='v4_shadow_decision')
    op.drop_index(op.f('ix_v4_shadow_decision_earnings_calendar_event_id'), table_name='v4_shadow_decision')
    op.drop_table('v4_shadow_decision')
    # ### end Alembic commands ###
