"""add research_preparation_job table

Revision ID: b412b07bf06d
Revises: 75655667cae0
Create Date: 2026-08-17 23:21:55.374339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b412b07bf06d'
down_revision: Union[str, Sequence[str], None] = '75655667cae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_preparation_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='research_job_status'), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_preparation_job_company_id'), 'research_preparation_job', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_preparation_job_ticker'), 'research_preparation_job', ['ticker'], unique=False)
    # NOTE: autogenerate also wants to drop ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # autogenerate can't see as ORM-managed. Manually stripped; see prior
    # migrations.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_preparation_job_ticker'), table_name='research_preparation_job')
    op.drop_index(op.f('ix_research_preparation_job_company_id'), table_name='research_preparation_job')
    op.drop_table('research_preparation_job')
    # ### end Alembic commands ###
    # op.drop_table() does not drop the enum type it implicitly created on
    # upgrade -- without this, a later re-upgrade fails with DuplicateObject
    # on CREATE TYPE. Same fix as 0e4a99eca9fb's market_data_quality enum.
    sa.Enum(name='research_job_status').drop(op.get_bind(), checkfirst=True)
