"""core schema: company, earnings_event, expectation snapshot, result, price reaction, options snapshot, volatility snapshot, filing

Revision ID: c535e22e3a6d
Revises: 
Create Date: 2026-08-17 01:00:56.726080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c535e22e3a6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_cik'), 'company', ['cik'], unique=True)
    op.create_index(op.f('ix_company_ticker'), 'company', ['ticker'], unique=True)
    op.create_table('earnings_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('announcement_time', sa.Enum('BEFORE_MARKET', 'AFTER_MARKET', 'UNKNOWN', name='announcement_time'), nullable=False),
    sa.Column('date_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'fiscal_quarter', name='uq_earnings_event')
    )
    op.create_index(op.f('ix_earnings_event_company_id'), 'earnings_event', ['company_id'], unique=False)
    op.create_index(op.f('ix_earnings_event_earnings_date'), 'earnings_event', ['earnings_date'], unique=False)
    op.create_table('filing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.Enum('FORM_10K', 'FORM_10Q', 'FORM_8K', 'EARNINGS_RELEASE', 'INVESTOR_PRESENTATION', 'OTHER', name='filing_type'), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=32), nullable=True),
    sa.Column('accession_number', sa.String(length=32), nullable=True),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_accession_number'), 'filing', ['accession_number'], unique=True)
    op.create_index(op.f('ix_filing_company_id'), 'filing', ['company_id'], unique=False)
    op.create_index(op.f('ix_filing_filing_date'), 'filing', ['filing_date'], unique=False)
    op.create_table('earnings_expectation_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consensus_eps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('consensus_revenue', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('previous_guidance', sa.String(), nullable=True),
    sa.Column('analyst_revision_direction', sa.Enum('UP', 'DOWN', 'FLAT', 'UNKNOWN', name='revision_direction'), nullable=False),
    sa.Column('stock_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('atm_implied_volatility', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('implied_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('implied_move_absolute', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iv_percentile', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('near_term_iv', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('next_term_iv', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('term_structure_slope', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('put_call_open_interest_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('put_call_volume_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recent_return_5d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recent_return_20d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sector_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_return', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('earnings_event_id', 'snapshot_timestamp', 'source_provider', name='uq_expectation_snapshot')
    )
    op.create_index(op.f('ix_earnings_expectation_snapshot_earnings_event_id'), 'earnings_expectation_snapshot', ['earnings_event_id'], unique=False)
    op.create_index(op.f('ix_earnings_expectation_snapshot_snapshot_timestamp'), 'earnings_expectation_snapshot', ['snapshot_timestamp'], unique=False)
    op.create_table('earnings_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_eps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('actual_revenue', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('guidance_text', sa.String(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_result_earnings_event_id'), 'earnings_result', ['earnings_event_id'], unique=True)
    op.create_table('options_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('option_type', sa.Enum('CALL', 'PUT', name='option_type'), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('greeks_source', sa.Enum('PROVIDER', 'BLACK_SCHOLES', name='greeks_source'), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'snapshot_timestamp', 'expiration_date', 'strike', 'option_type', 'source_provider', name='uq_options_snapshot')
    )
    op.create_index(op.f('ix_options_snapshot_company_id'), 'options_snapshot', ['company_id'], unique=False)
    op.create_index(op.f('ix_options_snapshot_earnings_event_id'), 'options_snapshot', ['earnings_event_id'], unique=False)
    op.create_index(op.f('ix_options_snapshot_expiration_date'), 'options_snapshot', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_options_snapshot_snapshot_timestamp'), 'options_snapshot', ['snapshot_timestamp'], unique=False)
    op.create_table('price_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=False),
    sa.Column('close_price_before', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('after_hours_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('next_day_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('five_day_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('after_hours_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('next_day_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('five_day_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_reaction_earnings_event_id'), 'price_reaction', ['earnings_event_id'], unique=True)
    op.create_table('volatility_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('near_term_expiration', sa.Date(), nullable=True),
    sa.Column('next_term_expiration', sa.Date(), nullable=True),
    sa.Column('atm_iv_near', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('atm_iv_next', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('term_structure_slope', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iv_percentile', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('implied_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('implied_move_absolute', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'snapshot_timestamp', 'method', name='uq_volatility_snapshot')
    )
    op.create_index(op.f('ix_volatility_snapshot_company_id'), 'volatility_snapshot', ['company_id'], unique=False)
    op.create_index(op.f('ix_volatility_snapshot_earnings_event_id'), 'volatility_snapshot', ['earnings_event_id'], unique=False)
    op.create_index(op.f('ix_volatility_snapshot_snapshot_timestamp'), 'volatility_snapshot', ['snapshot_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volatility_snapshot_snapshot_timestamp'), table_name='volatility_snapshot')
    op.drop_index(op.f('ix_volatility_snapshot_earnings_event_id'), table_name='volatility_snapshot')
    op.drop_index(op.f('ix_volatility_snapshot_company_id'), table_name='volatility_snapshot')
    op.drop_table('volatility_snapshot')
    op.drop_index(op.f('ix_price_reaction_earnings_event_id'), table_name='price_reaction')
    op.drop_table('price_reaction')
    op.drop_index(op.f('ix_options_snapshot_snapshot_timestamp'), table_name='options_snapshot')
    op.drop_index(op.f('ix_options_snapshot_expiration_date'), table_name='options_snapshot')
    op.drop_index(op.f('ix_options_snapshot_earnings_event_id'), table_name='options_snapshot')
    op.drop_index(op.f('ix_options_snapshot_company_id'), table_name='options_snapshot')
    op.drop_table('options_snapshot')
    op.drop_index(op.f('ix_earnings_result_earnings_event_id'), table_name='earnings_result')
    op.drop_table('earnings_result')
    op.drop_index(op.f('ix_earnings_expectation_snapshot_snapshot_timestamp'), table_name='earnings_expectation_snapshot')
    op.drop_index(op.f('ix_earnings_expectation_snapshot_earnings_event_id'), table_name='earnings_expectation_snapshot')
    op.drop_table('earnings_expectation_snapshot')
    op.drop_index(op.f('ix_filing_filing_date'), table_name='filing')
    op.drop_index(op.f('ix_filing_company_id'), table_name='filing')
    op.drop_index(op.f('ix_filing_accession_number'), table_name='filing')
    op.drop_table('filing')
    op.drop_index(op.f('ix_earnings_event_earnings_date'), table_name='earnings_event')
    op.drop_index(op.f('ix_earnings_event_company_id'), table_name='earnings_event')
    op.drop_table('earnings_event')
    op.drop_index(op.f('ix_company_ticker'), table_name='company')
    op.drop_index(op.f('ix_company_cik'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
