"""add ai research query and thesis version tables

Revision ID: ca982f68c4af
Revises: f9282e8f03a4
Create Date: 2026-08-18 21:11:49.883048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca982f68c4af'
down_revision: Union[str, Sequence[str], None] = 'f9282e8f03a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_research_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('intent_category', sa.String(length=64), nullable=False),
    sa.Column('planning_method', sa.String(length=64), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('verification_ran', sa.Boolean(), nullable=False),
    sa.Column('verification_supported', sa.Boolean(), nullable=True),
    sa.Column('revised', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_research_query_company_id'), 'ai_research_query', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_research_query_ticker'), 'ai_research_query', ['ticker'], unique=False)
    op.create_table('ai_thesis_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('business_context', sa.Text(), nullable=False),
    sa.Column('historical_earnings_pattern', sa.Text(), nullable=False),
    sa.Column('guidance_trend', sa.Text(), nullable=False),
    sa.Column('key_risks', sa.Text(), nullable=False),
    sa.Column('market_setup', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('earnings_estimate_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('volatility_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['earnings_estimate_snapshot_id'], ['earnings_estimate_snapshot.id'], ),
    sa.ForeignKeyConstraint(['volatility_snapshot_id'], ['volatility_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_thesis_version_company_id'), 'ai_thesis_version', ['company_id'], unique=False)
    # NOTE: autogenerate wrongly proposed dropping ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts here -- those were created via raw op.execute()
    # in an earlier migration (not SQLAlchemy ORM metadata), so autogenerate's
    # model-vs-DB diff sees them as "not declared" and wants to remove them. They
    # are real, load-bearing indexes (see 74c62fe04b0b) and are intentionally left
    # alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_thesis_version_company_id'), table_name='ai_thesis_version')
    op.drop_table('ai_thesis_version')
    op.drop_index(op.f('ix_ai_research_query_ticker'), table_name='ai_research_query')
    op.drop_index(op.f('ix_ai_research_query_company_id'), table_name='ai_research_query')
    op.drop_table('ai_research_query')
    # ### end Alembic commands ###
