"""Add V4 DecisionView model/reasoning provenance and model-aware usage telemetry.

Revision ID: d2f4b6a81c37
Revises: c1e5a7d93f20
Create Date: 2026-09-02

Hand-written and additive only (autogenerate would try to drop the
APScheduler and RAG tables it does not know about). Nullable columns:
existing rows keep their stored identity untouched -- historical views
generated by deepseek-v4-flash are not rewritten (they simply have no
thinking/returned-model provenance, which is the honest state).
"""

from alembic import op
import sqlalchemy as sa

revision = "d2f4b6a81c37"
down_revision = "c1e5a7d93f20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("v4_shadow_decision") as batch:
        batch.add_column(sa.Column("llm_returned_model", sa.String(128), nullable=True))
        batch.add_column(sa.Column("llm_thinking", sa.String(16), nullable=True))
        batch.add_column(sa.Column("llm_reasoning_effort", sa.String(16), nullable=True))
        batch.add_column(sa.Column("llm_max_tokens", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("llm_finish_reason", sa.String(32), nullable=True))
        batch.add_column(sa.Column("llm_input_tokens", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("llm_output_tokens", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("llm_reasoning_tokens", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("llm_cache_hit_tokens", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("llm_latency_ms", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("llm_config_version", sa.String(48), nullable=True))
    with op.batch_alter_table("provider_usage_event") as batch:
        batch.add_column(sa.Column("model", sa.String(128), nullable=True))
        batch.add_column(sa.Column("reasoning_effort", sa.String(16), nullable=True))
        batch.add_column(sa.Column("reasoning_tokens", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("cache_hit_tokens", sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("provider_usage_event") as batch:
        for name in ("cache_hit_tokens", "reasoning_tokens", "reasoning_effort", "model"):
            batch.drop_column(name)
    with op.batch_alter_table("v4_shadow_decision") as batch:
        for name in (
            "llm_config_version",
            "llm_latency_ms",
            "llm_cache_hit_tokens",
            "llm_reasoning_tokens",
            "llm_output_tokens",
            "llm_input_tokens",
            "llm_finish_reason",
            "llm_max_tokens",
            "llm_reasoning_effort",
            "llm_thinking",
            "llm_returned_model",
        ):
            batch.drop_column(name)
