"""add put/call ratio columns to volatility_snapshot

Revision ID: dd02627a107f
Revises: 81cec62d0ba7
Create Date: 2026-08-17 18:08:30.478364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd02627a107f'
down_revision: Union[str, Sequence[str], None] = '81cec62d0ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate wants to drop ix_document_chunk_embedding_hnsw and
    # ix_document_chunk_text_fts every time -- both are raw-SQL indexes
    # (see the migration that created document_chunk) that autogenerate
    # can't see as ORM-managed. Manually stripped; see prior migrations.
    op.add_column(
        'volatility_snapshot',
        sa.Column('put_call_open_interest_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    )
    op.add_column(
        'volatility_snapshot',
        sa.Column('put_call_volume_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volatility_snapshot', 'put_call_volume_ratio')
    op.drop_column('volatility_snapshot', 'put_call_open_interest_ratio')
    # ### end Alembic commands ###
