"""add ai decision version table and strategy risk preference

Revision ID: e435021adcc4
Revises: ca982f68c4af
Create Date: 2026-08-19 00:22:07.338349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e435021adcc4'
down_revision: Union[str, Sequence[str], None] = 'ca982f68c4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decision_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('STRONG_BULLISH', 'BULLISH', 'NEUTRAL', 'BEARISH', 'STRONG_BEARISH', name='decision_direction'), nullable=False),
    sa.Column('volatility_view', sa.Enum('LONG_VOL', 'NEUTRAL_VOL', 'SHORT_VOL', name='decision_volatility_view'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_components', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('key_catalysts', sa.Text(), nullable=False),
    sa.Column('key_risks', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('decision_source', sa.Enum('AI', 'MANUAL_OVERRIDE', name='decision_source'), nullable=False),
    sa.Column('risk_preference', sa.String(length=32), nullable=False),
    sa.Column('recommended_strategy_category', sa.String(length=32), nullable=True),
    sa.Column('recommended_strategy_legs', sa.JSON(), nullable=True),
    sa.Column('recommended_strategy_analysis', sa.JSON(), nullable=True),
    sa.Column('recommended_strategy_score', sa.Integer(), nullable=True),
    sa.Column('recommended_strategy_score_components', sa.JSON(), nullable=True),
    sa.Column('recommended_strategy_why', sa.JSON(), nullable=True),
    sa.Column('recommended_strategy_risks', sa.JSON(), nullable=True),
    sa.Column('alternative_strategies', sa.JSON(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('underlying_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('implied_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('earnings_estimate_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('volatility_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'SETTLED', 'VOID', name='decision_status'), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('earnings_event_id', sa.Integer(), nullable=True),
    sa.Column('actual_next_day_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('actual_five_day_move_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.Column('actual_move_exceeded_implied', sa.Boolean(), nullable=True),
    sa.Column('breakeven_met', sa.Boolean(), nullable=True),
    sa.Column('strategy_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('strategy_pnl_available', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['earnings_estimate_snapshot_id'], ['earnings_estimate_snapshot.id'], ),
    sa.ForeignKeyConstraint(['earnings_event_id'], ['earnings_event.id'], ),
    sa.ForeignKeyConstraint(['volatility_snapshot_id'], ['volatility_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decision_version_company_id'), 'ai_decision_version', ['company_id'], unique=False)
    op.add_column('app_provider_settings', sa.Column('strategy_risk_preference', sa.String(length=32), nullable=True))
    # NOTE: autogenerate also detected 'removed' ix_document_chunk_embedding_hnsw
    # and ix_document_chunk_text_fts -- a known recurring false positive
    # (these indexes use postgresql_ops/expressions Alembic's comparator
    # can't reflect exactly, so it thinks they changed when they haven't;
    # see prior migrations' same note). Deliberately not dropped/recreated
    # here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_provider_settings', 'strategy_risk_preference')
    op.drop_index(op.f('ix_ai_decision_version_company_id'), table_name='ai_decision_version')
    op.drop_table('ai_decision_version')
    # ### end Alembic commands ###
    # op.drop_table() does not drop the enum types it implicitly created on
    # upgrade -- without this, a later re-upgrade fails with DuplicateObject
    # on CREATE TYPE (same fix as b412b07bf06d's research_job_status enum).
    sa.Enum(name='decision_direction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='decision_volatility_view').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='decision_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='decision_status').drop(op.get_bind(), checkfirst=True)
