"""v4.2 challenger evidence, chain metadata freeze, and leg size capture

Additive only. Hand-written rather than autogenerated: this repository has a
history of ``alembic revision --autogenerate`` proposing to drop
``apscheduler_jobs``, the RAG HNSW index and the FTS index, so every
operation below is written and audited by hand. Nothing here touches V4.1
evidence, research, calendar, provider or scheduler tables.

Three things arrive:

1. ``v4_chain_metadata_snapshot`` -- the listed expirations and strikes that
   existed at a decision instant. Shared point-in-time evidence, not
   challenger-specific: without it a multi-expiry replay is impossible, which
   is exactly why the seven historical events cannot have one. Metadata only;
   freezing it costs no market-data subscription.

2. ``v4_2_challenger_decision`` / ``_candidate`` / ``_config_result`` -- the
   challenger's own append-only record, kept entirely separate from the
   control's so a challenger can never rewrite the evidence it is measured
   against.

3. ``bid_size`` / ``ask_size`` on ``v4_shadow_candidate_leg`` -- additive,
   nullable, and read by nothing. The provider already receives these ticks;
   only persistence dropped them. NULL means not provided and is deliberately
   distinguishable from a real 0.

Revision ID: e5b7c9d1f3a4
Revises: d1f3a5c7e9b2
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "e5b7c9d1f3a4"
down_revision = "d1f3a5c7e9b2"
branch_labels = None
depends_on = None

_IMMUTABLE = (
    "v4_chain_metadata_snapshot",
    "v4_2_challenger_decision",
    "v4_2_challenger_candidate",
    "v4_2_challenger_config_result",
)


def upgrade() -> None:
    op.create_table(
        "v4_chain_metadata_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("earnings_calendar_event_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("underlying_conid", sa.String(length=32), nullable=True),
        sa.Column("trading_class", sa.String(length=32), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=True),
        sa.Column("multiplier", sa.String(length=16), nullable=True),
        sa.Column("available_expirations", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("listed_strikes", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("considered_expirations", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("source_provider", sa.String(length=64), nullable=True),
        sa.Column("metadata_quality", sa.String(length=24), nullable=True),
        sa.Column("expiry_ladder_version", sa.String(length=48), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["earnings_calendar_event_id"], ["earnings_calendar_event.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("earnings_calendar_event_id", "observed_at",
                            name="uq_v4_chain_metadata_event_window"),
    )
    op.create_index("ix_v4_chain_metadata_snapshot_earnings_calendar_event_id",
                    "v4_chain_metadata_snapshot", ["earnings_calendar_event_id"])
    op.create_index("ix_v4_chain_metadata_ticker", "v4_chain_metadata_snapshot", ["ticker"])

    op.create_table(
        "v4_2_challenger_decision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("earnings_calendar_event_id", sa.Integer(), nullable=False),
        sa.Column("shadow_decision_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=48), nullable=False),
        sa.Column("gate_version", sa.String(length=48), nullable=False),
        sa.Column("move_edge_version", sa.String(length=48), nullable=False),
        sa.Column("move_distribution_version", sa.String(length=48), nullable=True),
        sa.Column("reaction_anchoring_version", sa.String(length=48), nullable=True),
        sa.Column("expiry_ladder_version", sa.String(length=48), nullable=True),
        sa.Column("friction_version", sa.String(length=48), nullable=True),
        sa.Column("ranking_version", sa.String(length=64), nullable=True),
        sa.Column("decision_view_schema_version", sa.String(length=48), nullable=True),
        sa.Column("historical_sample_n", sa.Integer(), nullable=True),
        sa.Column("historical_evidence_quality", sa.String(length=32), nullable=True),
        sa.Column("historical_timing_quality", sa.String(length=32), nullable=True),
        sa.Column("historical_median_abs_move_pct", sa.Numeric(18, 8), nullable=True),
        sa.Column("historical_p25_abs_move_pct", sa.Numeric(18, 8), nullable=True),
        sa.Column("historical_p75_abs_move_pct", sa.Numeric(18, 8), nullable=True),
        sa.Column("historical_source_digest", sa.String(length=64), nullable=True),
        sa.Column("historical_source_event_count", sa.Integer(), nullable=True),
        sa.Column("historical_as_of", sa.Date(), nullable=True),
        sa.Column("implied_move_pct", sa.Numeric(18, 8), nullable=True),
        sa.Column("underlying_price", sa.Numeric(18, 6), nullable=True),
        sa.Column("market_data_quality", sa.String(length=24), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("selected_candidate_id", sa.String(length=128), nullable=True),
        sa.Column("no_action_reason", sa.Text(), nullable=True),
        sa.Column("candidates_evaluated", sa.Integer(), nullable=False),
        sa.Column("candidates_accepted", sa.Integer(), nullable=False),
        sa.Column("total_latency_ms", sa.Numeric(18, 3), nullable=True),
        sa.Column("metadata_request_count", sa.Integer(), nullable=True),
        sa.Column("contract_detail_request_count", sa.Integer(), nullable=True),
        sa.Column("market_data_request_count", sa.Integer(), nullable=True),
        sa.Column("unique_contracts_quoted", sa.Integer(), nullable=True),
        sa.Column("reused_control_contracts", sa.Integer(), nullable=True),
        sa.Column("failure_category", sa.String(length=48), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["earnings_calendar_event_id"], ["earnings_calendar_event.id"]),
        sa.ForeignKeyConstraint(["shadow_decision_id"], ["v4_shadow_decision.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("earnings_calendar_event_id", "gate_version", "observed_at",
                            name="uq_v4_2_challenger_decision_event_version_window"),
    )
    op.create_index("ix_v4_2_challenger_decision_earnings_calendar_event_id",
                    "v4_2_challenger_decision", ["earnings_calendar_event_id"])
    op.create_index("ix_v4_2_challenger_decision_shadow_decision_id",
                    "v4_2_challenger_decision", ["shadow_decision_id"])
    op.create_index("ix_v4_2_challenger_decision_status", "v4_2_challenger_decision", ["status"])
    op.create_index("ix_v4_2_challenger_decision_ticker", "v4_2_challenger_decision", ["ticker"])

    op.create_table(
        "v4_2_challenger_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenger_decision_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.String(length=128), nullable=False),
        sa.Column("strategy", sa.String(length=48), nullable=False),
        sa.Column("expiration", sa.Date(), nullable=False),
        sa.Column("expiry_ladder_position", sa.Integer(), nullable=True),
        sa.Column("entry_dte", sa.Integer(), nullable=True),
        sa.Column("dte_at_settlement", sa.Integer(), nullable=True),
        sa.Column("settlement_risk", sa.String(length=48), nullable=True),
        sa.Column("geometry_variant_id", sa.String(length=64), nullable=True),
        sa.Column("semantic_compatibility", sa.Numeric(18, 6), nullable=True),
        sa.Column("semantic_tier", sa.String(length=24), nullable=True),
        sa.Column("core_median_return", sa.Numeric(18, 6), nullable=True),
        sa.Column("core_worst_return", sa.Numeric(18, 6), nullable=True),
        sa.Column("core_best_return", sa.Numeric(18, 6), nullable=True),
        sa.Column("core_positive_scenario_fraction", sa.Numeric(18, 6), nullable=True),
        sa.Column("no_profitable_region", sa.Boolean(), nullable=True),
        sa.Column("move_edge_status", sa.String(length=32), nullable=True),
        sa.Column("move_edge_exposure", sa.String(length=16), nullable=True),
        sa.Column("move_edge_ratio", sa.Numeric(18, 8), nullable=True),
        sa.Column("move_edge_threshold", sa.Numeric(18, 8), nullable=True),
        sa.Column("move_edge_explanation", sa.Text(), nullable=True),
        sa.Column("mean_relative_spread", sa.Numeric(18, 6), nullable=True),
        sa.Column("worst_relative_spread", sa.Numeric(18, 6), nullable=True),
        sa.Column("min_bid_size", sa.Integer(), nullable=True),
        sa.Column("min_ask_size", sa.Integer(), nullable=True),
        sa.Column("total_volume", sa.Integer(), nullable=True),
        sa.Column("min_open_interest", sa.Integer(), nullable=True),
        sa.Column("legs_with_empty_bid", sa.Integer(), nullable=True),
        sa.Column("capital_utilisation", sa.Numeric(18, 6), nullable=True),
        sa.Column("entry_cash_required", sa.Numeric(18, 6), nullable=True),
        sa.Column("viability_acceptable", sa.Boolean(), nullable=False),
        sa.Column("viability_reason_codes", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("viability_detail", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("legs_json", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("market_data_quality", sa.String(length=24), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["challenger_decision_id"], ["v4_2_challenger_decision.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenger_decision_id", "candidate_id",
                            name="uq_v4_2_challenger_candidate_one_per_decision"),
    )
    op.create_index("ix_v4_2_challenger_candidate_challenger_decision_id",
                    "v4_2_challenger_candidate", ["challenger_decision_id"])

    op.create_table(
        "v4_2_challenger_config_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenger_decision_id", sa.Integer(), nullable=False),
        sa.Column("configuration_key", sa.String(length=48), nullable=False),
        sa.Column("capital_base", sa.Numeric(18, 2), nullable=False),
        sa.Column("risk_profile", sa.String(length=24), nullable=False),
        sa.Column("max_risk_dollars", sa.Numeric(18, 2), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("selected_candidate_id", sa.String(length=128), nullable=True),
        sa.Column("no_action_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["challenger_decision_id"], ["v4_2_challenger_decision.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenger_decision_id", "configuration_key",
                            name="uq_v4_2_challenger_config_one_per_decision"),
    )
    op.create_index("ix_v4_2_challenger_config_result_challenger_decision_id",
                    "v4_2_challenger_config_result", ["challenger_decision_id"])

    # Additive, nullable, read by nothing today. NULL = not provided, which
    # must stay distinguishable from a real size of 0.
    op.add_column("v4_shadow_candidate_leg", sa.Column("bid_size", sa.Integer(), nullable=True))
    op.add_column("v4_shadow_candidate_leg", sa.Column("ask_size", sa.Integer(), nullable=True))

    # Append-only, using the SAME trigger function every other V4 evidence
    # table installs. Owned by an earlier migration and deliberately not
    # redefined here.
    for table in _IMMUTABLE:
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION reject_snapshot_update();
            """
        )


def downgrade() -> None:
    for table in _IMMUTABLE:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update ON {table}")
    op.drop_column("v4_shadow_candidate_leg", "ask_size")
    op.drop_column("v4_shadow_candidate_leg", "bid_size")
    op.drop_table("v4_2_challenger_config_result")
    op.drop_table("v4_2_challenger_candidate")
    op.drop_table("v4_2_challenger_decision")
    op.drop_table("v4_chain_metadata_snapshot")
    # reject_snapshot_update() is NOT dropped: it is owned by the migration
    # that created it and is still used by every other evidence table.
